// Reefpedia — Tidepool Reef's species & pest encyclopedia.
// `wiki` is the Wikipedia page title used to fetch a freely-licensed photo at runtime.

export const REEFPEDIA_CATS = ["All", "Fish", "SPS", "LPS", "Soft", "Invert", "Pest"];

export const REEFPEDIA = [
  /* ============================ FISH ============================ */
  { id: "f1", cat: "Fish", name: "Ocellaris Clownfish", sci: "Amphiprion ocellaris", wiki: "Ocellaris clownfish", diff: "Easy", g: ["#ff7a5c", "#ffc24d"],
    facts: [["Max size", "3.5\""], ["Min tank", "10 gal"], ["Diet", "Omnivore — pellets, frozen"], ["Reef safe", "Yes"], ["Temperament", "Peaceful; pairs well"]],
    blurb: "The fish that launched a million reef tanks. Hardy, tank-bred everywhere, and full of personality. Buy two juveniles and they'll pair naturally — the larger becomes female. They'll host anemones, hammers, torches, or nothing at all and be perfectly happy." },
  { id: "f2", cat: "Fish", name: "Royal Gramma", sci: "Gramma loreto", wiki: "Royal gramma", diff: "Easy", g: ["#b06cff", "#ffc24d"],
    facts: [["Max size", "3\""], ["Min tank", "20 gal"], ["Diet", "Carnivore — mysis, brine"], ["Reef safe", "Yes"], ["Temperament", "Peaceful; cave dweller"]],
    blurb: "Purple-to-gold gradient in fish form. Loves rockwork caves and often hangs upside-down under ledges — that's normal, not illness. One per tank; two will fight. A perfect nano centerpiece fish." },
  { id: "f3", cat: "Fish", name: "Yellow Tang", sci: "Zebrasoma flavescens", wiki: "Yellow tang", diff: "Easy", g: ["#ffc24d", "#ff9d8a"],
    facts: [["Max size", "8\""], ["Min tank", "75 gal"], ["Diet", "Herbivore — nori, algae"], ["Reef safe", "Yes"], ["Temperament", "Semi-aggressive with tangs"]],
    blurb: "The classic reef-tank icon and a relentless algae grazer. Needs swimming room and daily greens (rubber-band nori to a rock). Tank-bred specimens are now available — worth seeking out. Add tangs last and together to minimize turf wars." },
  { id: "f4", cat: "Fish", name: "Purple Tang", sci: "Zebrasoma xanthurum", wiki: "Zebrasoma xanthurum", diff: "Medium", g: ["#b06cff", "#3f9bff"],
    facts: [["Max size", "9\""], ["Min tank", "100 gal"], ["Diet", "Herbivore — nori, algae"], ["Reef safe", "Yes"], ["Temperament", "Aggressive with other tangs"]],
    blurb: "Royal purple with a yellow tail — a showpiece fish. More attitude than its yellow cousin; introduce it last, and never house two Zebrasoma together in under 200 gallons. Prone to HLLE with poor diet, so feed greens heavily." },
  { id: "f5", cat: "Fish", name: "Blue (Hippo) Tang", sci: "Paracanthurus hepatus", wiki: "Paracanthurus", diff: "Medium", g: ["#3f9bff", "#ffc24d"],
    facts: [["Max size", "12\""], ["Min tank", "125 gal"], ["Diet", "Omnivore — heavy on greens"], ["Reef safe", "Yes"], ["Temperament", "Peaceful but skittish"]],
    blurb: "Dory grows to a foot long and is an ich magnet when stressed — quarantine is non-negotiable. Loves to wedge into rockwork when startled (or sleep on its side, which panics new owners). A big, active swimmer that truly needs a big tank." },
  { id: "f6", cat: "Fish", name: "Kole Tang", sci: "Ctenochaetus strigosus", wiki: "Ctenochaetus strigosus", diff: "Easy", g: ["#ff9d8a", "#b06cff"],
    facts: [["Max size", "5.5\""], ["Min tank", "70 gal"], ["Diet", "Detritivore — film algae"], ["Reef safe", "Yes"], ["Temperament", "Peaceful for a tang"]],
    blurb: "A bristletooth tang that hoovers film algae and diatoms off glass and rock all day — one of the most useful janitors that's also a beautiful fish. Smaller and more peaceful than most tangs, making it the best tang choice for mid-size tanks." },
  { id: "f7", cat: "Fish", name: "Flame Angelfish", sci: "Centropyge loricula", wiki: "Flame angelfish", diff: "Medium", g: ["#ff5d72", "#ffc24d"],
    facts: [["Max size", "4\""], ["Min tank", "70 gal"], ["Diet", "Omnivore"], ["Reef safe", "With caution"], ["Temperament", "Semi-aggressive"]],
    blurb: "Blazing red-orange with tiger bars — arguably the most stunning dwarf angel. The catch: 'reef safe' is a coin flip. Most behave; some develop a taste for LPS and clam mantles. Keep it well fed and watch it early. Worth the gamble for many." },
  { id: "f8", cat: "Fish", name: "Coral Beauty Angelfish", sci: "Centropyge bispinosa", wiki: "Twospined angelfish", diff: "Easy", g: ["#b06cff", "#ff7a5c"],
    facts: [["Max size", "4\""], ["Min tank", "55 gal"], ["Diet", "Omnivore"], ["Reef safe", "With caution"], ["Temperament", "Semi-aggressive"]],
    blurb: "Purple body, orange belly, hardy as they come — the beginner's dwarf angel. Same coral-nipping caveat as all Centropyge, but Coral Beauties are statistically among the best behaved. Give it rockwork to graze and patrol." },
  { id: "f9", cat: "Fish", name: "Melanurus Wrasse", sci: "Halichoeres melanurus", wiki: "Halichoeres melanurus", diff: "Easy", g: ["#2ee6c8", "#ff9d8a"],
    facts: [["Max size", "5\""], ["Min tank", "50 gal"], ["Diet", "Carnivore — pests included"], ["Reef safe", "Yes"], ["Temperament", "Peaceful; active"]],
    blurb: "The pest-control MVP: eats flatworms, pyramid snails, and comensal pests while looking like a neon painting. Needs a 2\"+ sand bed to sleep in — it dives in at lights-out and new keepers think it's escaped. Jumper; use a lid." },
  { id: "f10", cat: "Fish", name: "Six Line Wrasse", sci: "Pseudocheilinus hexataenia", wiki: "Pseudocheilinus hexataenia", diff: "Easy", g: ["#b06cff", "#3ce0a3"],
    facts: [["Max size", "3\""], ["Min tank", "30 gal"], ["Diet", "Carnivore — pests, pods"], ["Reef safe", "Yes"], ["Temperament", "Territorial with age"]],
    blurb: "Gorgeous, hardy, eats pests — and develops a Napoleon complex. Many six lines turn into tank bullies at year two, harassing new additions. Add it last, or choose a possum or pink-streaked wrasse for a gentler alternative." },
  { id: "f11", cat: "Fish", name: "Yellow Watchman Goby", sci: "Cryptocentrus cinctus", wiki: "Cryptocentrus cinctus", diff: "Easy", g: ["#ffc24d", "#3ce0a3"],
    facts: [["Max size", "4\""], ["Min tank", "20 gal"], ["Diet", "Carnivore — sinking pellets"], ["Reef safe", "Yes"], ["Temperament", "Peaceful; pairs w/ pistol"]],
    blurb: "The grumpy-faced burrow guard. Pair it with a tiger pistol shrimp for the best symbiosis show in the hobby — the blind shrimp digs, the goby stands watch, and they never separate. Feed sinking food near the burrow." },
  { id: "f12", cat: "Fish", name: "Diamond Goby", sci: "Valenciennea puellaris", wiki: "Valenciennea puellaris", diff: "Medium", g: ["#ffc24d", "#84a8ba"],
    facts: [["Max size", "6\""], ["Min tank", "55 gal"], ["Diet", "Carnivore — must target feed"], ["Reef safe", "Yes"], ["Temperament", "Peaceful"]],
    blurb: "A sand-sifting machine that keeps your bed white by chewing through it all day — and redecorating your aquascape with the spoils. The catch: many slowly starve in small tanks. Target feed and only keep in mature tanks with deep sand." },
  { id: "f13", cat: "Fish", name: "Firefish", sci: "Nemateleotris magnifica", wiki: "Nemateleotris magnifica", diff: "Easy", g: ["#ff9d8a", "#ff5d72"],
    facts: [["Max size", "3\""], ["Min tank", "10 gal"], ["Diet", "Carnivore — small frozen"], ["Reef safe", "Yes"], ["Temperament", "Timid; jumper!"]],
    blurb: "An elegant dart goby that hovers in the current flicking its dorsal fin. Peaceful to a fault and a legendary jumper — a tight lid is mandatory. Keep singly or as a mated pair; two random firefish will feud." },
  { id: "f14", cat: "Fish", name: "Green Mandarin", sci: "Synchiropus splendidus", wiki: "Synchiropus splendidus", diff: "Hard", g: ["#3ce0a3", "#ff7a5c"],
    facts: [["Max size", "3\""], ["Min tank", "30 gal mature"], ["Diet", "Copepods (live)"], ["Reef safe", "Yes"], ["Temperament", "Peaceful"]],
    blurb: "The most psychedelic fish in the ocean — and a specialist feeder that eats copepods nearly nonstop. Only add to a mature tank with a thriving pod population or a refugium, or buy one trained onto frozen food. Immune to ich thanks to its slime coat." },
  { id: "f15", cat: "Fish", name: "Tailspot Blenny", sci: "Ecsenius stigmatura", wiki: "Ecsenius stigmatura", diff: "Easy", g: ["#ffc24d", "#3f9bff"],
    facts: [["Max size", "2.5\""], ["Min tank", "10 gal"], ["Diet", "Herbivore lean — algae, pellets"], ["Reef safe", "Yes"], ["Temperament", "Peaceful"]],
    blurb: "Big eyes, eyeliner, and a perch-and-peek lifestyle — the best personality-per-inch in the hobby. Grazes film algae and accepts everything. Perfect nano fish; give it small holes in the rockwork to claim as home." },
  { id: "f16", cat: "Fish", name: "Lawnmower Blenny", sci: "Salarias fasciatus", wiki: "Salarias fasciatus", diff: "Easy", g: ["#84a8ba", "#3ce0a3"],
    facts: [["Max size", "5\""], ["Min tank", "40 gal"], ["Diet", "Herbivore — film/hair algae"], ["Reef safe", "Yes"], ["Temperament", "Peaceful; one per tank"]],
    blurb: "A face only a reefer could love and an appetite for hair algae that earns the name. Needs a tank with enough natural algae growth or supplemental nori — they can thin out in spotless tanks. Watch it mow the glass with that underbite." },
  { id: "f17", cat: "Fish", name: "Lyretail Anthias", sci: "Pseudanthias squamipinnis", wiki: "Sea goldie", diff: "Medium", g: ["#ff9d8a", "#ffc24d"],
    facts: [["Max size", "5\""], ["Min tank", "75 gal"], ["Diet", "Carnivore — feed 2-3x daily"], ["Reef safe", "Yes"], ["Temperament", "Haremic — 1 male + females"]],
    blurb: "Constant midwater motion and color — anthias make a reef look alive. Keep one male with several females; the dominant female becomes male if he's lost. High metabolism means multiple small feedings a day, so an auto feeder helps." },
  { id: "f18", cat: "Fish", name: "Banggai Cardinalfish", sci: "Pterapogon kauderni", wiki: "Banggai cardinalfish", diff: "Easy", g: ["#84a8ba", "#e9f7fc"],
    facts: [["Max size", "3\""], ["Min tank", "20 gal"], ["Diet", "Carnivore — frozen"], ["Reef safe", "Yes"], ["Temperament", "Peaceful; pairs only"]],
    blurb: "Striking black-and-silver with a slow, stately hover. Endangered in the wild — buy tank-bred only, which is widely available. A mouthbrooder: males carry eggs (and fry!) in their mouths. Keep a pair, not a group." },
  { id: "f19", cat: "Fish", name: "Pajama Cardinalfish", sci: "Sphaeramia nematoptera", wiki: "Pajama cardinalfish", diff: "Easy", g: ["#ffc24d", "#ff5d72"],
    facts: [["Max size", "3.5\""], ["Min tank", "30 gal"], ["Diet", "Carnivore — frozen"], ["Reef safe", "Yes"], ["Temperament", "Peaceful; groups OK"]],
    blurb: "Dressed by a committee that never met: polka-dot rear, striped middle, yellow face, red eyes. Nocturnal-leaning and happiest in small groups hovering under overhangs. Bulletproof beginner fish." },
  { id: "f20", cat: "Fish", name: "Midas Blenny", sci: "Ecsenius midas", wiki: "Ecsenius midas", diff: "Easy", g: ["#ffc24d", "#ff9d8a"],
    facts: [["Max size", "4\""], ["Min tank", "30 gal"], ["Diet", "Omnivore — mysis, pellets"], ["Reef safe", "Yes"], ["Temperament", "Mostly peaceful"]],
    blurb: "A golden eel-like blenny that swims midwater with anthias and mimics their color. Charismatic and hardy, with an unforgettable derpy face. Can occasionally nip at similarly-shaped fish like firefish — watch pairings." },

  /* ============================ SPS ============================ */
  { id: "s1", cat: "SPS", name: "Acropora millepora", sci: "Acropora millepora", wiki: "Acropora millepora", diff: "Hard", g: ["#2ee6c8", "#ff7a5c"],
    facts: [["Light", "High (250+ PAR)"], ["Flow", "High, random"], ["Placement", "Top third"], ["Alk stability", "Critical — ±0.2 dKH"], ["Growth", "Fast when happy"]],
    blurb: "The classic 'milli' — fuzzy polyps and candy colors. Like all acros, it punishes instability: alkalinity swings cause tissue loss faster than almost anything else. Master alk/cal/mag consistency before attempting. Rewards you with the best colors in the hobby." },
  { id: "s2", cat: "SPS", name: "Acropora tenuis", sci: "Acropora tenuis", wiki: "Acropora tenuis", diff: "Hard", g: ["#ff7a5c", "#b06cff"],
    facts: [["Light", "High (250+ PAR)"], ["Flow", "High"], ["Placement", "Top third"], ["Alk stability", "Critical"], ["Growth", "Moderate-fast"]],
    blurb: "Home of the legendary high-end morphs (Walt Disney, Homewrecker). Tabling growth form with contrasting polyp colors. Same rules as every acro: rock-stable parameters, strong light, and patience — colors take months to fully develop." },
  { id: "s3", cat: "SPS", name: "Green Slimer", sci: "Acropora yongei", wiki: "Acropora yongei", diff: "Medium", g: ["#3ce0a3", "#2ee6c8"],
    facts: [["Light", "Med-High"], ["Flow", "High"], ["Placement", "Mid to top"], ["Alk stability", "Important"], ["Growth", "Very fast"]],
    blurb: "The gateway acro. Forgiving (by acro standards), neon green, and grows so fast you'll be fragging it quarterly. Named for the impressive slime it produces when handled. If you can keep a slimer thriving for six months, you're ready for harder acros." },
  { id: "s4", cat: "SPS", name: "Montipora capricornis", sci: "Montipora capricornis", wiki: "Montipora capricornis", diff: "Medium", g: ["#ff5d72", "#ffc24d"],
    facts: [["Light", "Medium"], ["Flow", "Medium"], ["Placement", "Mid"], ["Watch for", "Montipora-eating nudibranchs"], ["Growth", "Fast, plating"]],
    blurb: "Plating whorls that build reef-scape architecture like nothing else. Much more forgiving than Acropora — the right first SPS after birdsnest. Inspect frags closely for Monti-eating nudibranchs (tiny white fluff); they're its one nemesis." },
  { id: "s5", cat: "SPS", name: "Montipora digitata", sci: "Montipora digitata", wiki: "Montipora digitata", diff: "Easy", g: ["#ffc24d", "#ff7a5c"],
    facts: [["Light", "Medium"], ["Flow", "Medium-High"], ["Placement", "Mid"], ["Alk stability", "Moderate"], ["Growth", "Fast, branching"]],
    blurb: "Branching fingers in orange, green, or the coveted Forest Fire morph. One of the easiest SPS in the hobby and a confidence builder — it tolerates parameter wobble that would strip an acro. Frags with a snip of scissors." },
  { id: "s6", cat: "SPS", name: "Birdsnest Coral", sci: "Seriatopora hystrix", wiki: "Seriatopora hystrix", diff: "Easy", g: ["#ff9d8a", "#3ce0a3"],
    facts: [["Light", "Medium"], ["Flow", "Medium-High"], ["Placement", "Mid"], ["Alk stability", "Moderate"], ["Growth", "Very fast, thin branches"]],
    blurb: "Delicate needle-thin branches that grow into a dense thicket shockingly fast. The classic first SPS. Brittle — branches snap easily, but every broken piece is a new frag. Thin it periodically or it shades itself out." },
  { id: "s7", cat: "SPS", name: "Stylophora", sci: "Stylophora pistillata", wiki: "Stylophora pistillata", diff: "Medium", g: ["#b06cff", "#ff9d8a"],
    facts: [["Light", "Med-High"], ["Flow", "High"], ["Placement", "Mid to top"], ["Alk stability", "Important"], ["Growth", "Moderate, blunt branches"]],
    blurb: "Cat's-paw growth with blunt rounded tips — the 'Milka' purple morph is a stunner. Sits between birdsnest and acropora in difficulty. A major research species: more is known about Stylo biology than nearly any other coral." },
  { id: "s8", cat: "SPS", name: "Pocillopora", sci: "Pocillopora damicornis", wiki: "Pocillopora damicornis", diff: "Easy", g: ["#ff9d8a", "#b06cff"],
    facts: [["Light", "Medium"], ["Flow", "Medium-High"], ["Placement", "Anywhere"], ["Quirk", "Self-seeds via polyp bailout"], ["Growth", "Fast, fuzzy"]],
    blurb: "Fuzzy cauliflower branches that tolerate almost anything. Famous for 'polyp bailout' — stressed colonies release polyps that settle elsewhere in the tank, so don't be surprised by surprise babies on your rockwork years later." },
  { id: "s9", cat: "SPS", name: "Porites", sci: "Porites", wiki: "Porites", diff: "Medium", g: ["#ffc24d", "#3ce0a3"],
    facts: [["Light", "High"], ["Flow", "High"], ["Placement", "Top"], ["Bonus", "Hosts Christmas tree worms"], ["Growth", "Slow, massive"]],
    blurb: "The reef's slow-and-steady boulder builder — wild colonies live for centuries. In tanks it's prized as the host rock for Christmas tree worms. Unremarkable growth rate, remarkable permanence." },
  { id: "s10", cat: "SPS", name: "Cactus Coral (Pavona)", sci: "Pavona cactus", wiki: "Pavona cactus", diff: "Easy", g: ["#84a8ba", "#3ce0a3"],
    facts: [["Light", "Medium"], ["Flow", "Medium"], ["Placement", "Mid"], ["Alk stability", "Forgiving"], ["Growth", "Fast, ruffled plates"]],
    blurb: "Ruffled potato-chip plates with a subtle glow under blues. Criminally underrated as a beginner SPS — hardy, fast, and architectural. Gives that SPS-dominant look without the SPS-dominant anxiety." },

  /* ============================ LPS ============================ */
  { id: "l1", cat: "LPS", name: "Hammer Coral", sci: "Euphyllia ancora", wiki: "Euphyllia ancora", diff: "Easy", g: ["#ffc24d", "#3fe3ff"],
    facts: [["Light", "Low-Medium"], ["Flow", "Low-Medium"], ["Placement", "Mid, with space"], ["Sweepers", "Yes — 6\" reach at night"], ["Growth", "Splits heads readily"]],
    blurb: "Flowing hammer-shaped tentacles in constant motion — the heartbeat of a mixed reef. Give it real estate: sweeper tentacles sting neighbors at night. Clownfish often host it. Wall hammers are touchier than branching; buy branching." },
  { id: "l2", cat: "LPS", name: "Torch Coral", sci: "Euphyllia glabrescens", wiki: "Euphyllia glabrescens", diff: "Medium", g: ["#ffc24d", "#ff7a5c"],
    facts: [["Light", "Low-Medium"], ["Flow", "Low-Medium"], ["Placement", "Mid, isolated"], ["Sweepers", "Potent — keep 6\"+ from all"], ["Growth", "Slow head splits"]],
    blurb: "Long flowing polyps with glowing tips — the hobby's status symbol (gold torches, Holy Grails). The most potent stinger of the Euphyllia family and slightly more sensitive than hammers. Dips and QT matter: torches are prone to hitchhiking pests." },
  { id: "l3", cat: "LPS", name: "Frogspawn", sci: "Euphyllia divisa", wiki: "Euphyllia divisa", diff: "Easy", g: ["#3ce0a3", "#b06cff"],
    facts: [["Light", "Low-Medium"], ["Flow", "Low-Medium"], ["Placement", "Mid"], ["Sweepers", "Yes"], ["Growth", "Moderate"]],
    blurb: "Branch-tipped polyps like clusters of frog eggs. Everything that applies to hammers applies here — Euphyllia can touch each other without stinging, so build a 'Euphyllia garden' of hammers, torches, and frogspawn together." },
  { id: "l4", cat: "LPS", name: "Duncan Coral", sci: "Duncanopsammia axifuga", wiki: "Duncanopsammia", diff: "Easy", g: ["#3fe3ff", "#2ee6c8"],
    facts: [["Light", "Low-Medium"], ["Flow", "Low"], ["Placement", "Low to mid"], ["Feeding", "Loves mysis/pellets"], ["Growth", "Fast when fed"]],
    blurb: "Green disco-polyps on stalks that multiply astonishingly fast when fed. Practically begs for food — polyps snatch mysis mid-water. One head becomes twenty in a year. Possibly the best value LPS in the hobby." },
  { id: "l5", cat: "LPS", name: "Acan Lord", sci: "Micromussa lordhowensis", wiki: "Micromussa lordhowensis", diff: "Easy", g: ["#b06cff", "#ff5d72"],
    facts: [["Light", "Low-Medium"], ["Flow", "Low"], ["Placement", "Bottom, sandbed OK"], ["Feeding", "Target feed for speed"], ["Growth", "Moderate"]],
    blurb: "Rainbow donuts of the sandbed. Reclassified from Acanthastrea to Micromussa but everyone still says 'acan.' Fleshy polyps expand at night to feed — target feed mysis weekly and watch colonies double. Endless collectible morphs." },
  { id: "l6", cat: "LPS", name: "Candy Cane Coral", sci: "Caulastraea furcata", wiki: "Caulastraea", diff: "Easy", g: ["#2ee6c8", "#3fe3ff"],
    facts: [["Light", "Low-Medium"], ["Flow", "Low-Medium"], ["Placement", "Low to mid"], ["Sweepers", "Short — polite neighbor"], ["Growth", "Steady head splits"]],
    blurb: "Trumpet-shaped heads with pinstripe glow. One of the politest LPS — short sweepers, modest needs, steady splitting. A perfect first splurge coral: hard to kill, satisfying to grow, easy to frag with bone cutters." },
  { id: "l7", cat: "LPS", name: "War Coral (Favites)", sci: "Favites pentagona", wiki: "Favites", diff: "Easy", g: ["#ff5d72", "#3ce0a3"],
    facts: [["Light", "Medium"], ["Flow", "Medium"], ["Placement", "Mid"], ["Sweepers", "Long at night — beware"], ["Growth", "Encrusting"]],
    blurb: "Red-and-green honeycomb warfare. Beautiful, hardy, and armed — night sweepers will burn anything within a few inches, hence the name. Feeds aggressively after lights out. Encrusts over rockwork like living armor." },
  { id: "l8", cat: "LPS", name: "Chalice Coral", sci: "Echinophyllia", wiki: "Echinophyllia", diff: "Medium", g: ["#ff5d72", "#3fe3ff"],
    facts: [["Light", "Low-Medium"], ["Flow", "Low"], ["Placement", "Low; angle for growth"], ["Warning", "Colors fade in high light"], ["Growth", "Slow plates"]],
    blurb: "Psychedelic plates with contrasting eyes — the collector's coral (Miami Hurricane, Mummy Eye). Less light than you think: high PAR browns them out. Slow growers that reward patience with jaw-dropping color development." },
  { id: "l9", cat: "LPS", name: "Blastomussa", sci: "Blastomussa wellsi", wiki: "Blastomussa", diff: "Easy", g: ["#ff5d72", "#b06cff"],
    facts: [["Light", "Low"], ["Flow", "Low"], ["Placement", "Bottom, shaded OK"], ["Feeding", "Optional"], ["Growth", "Slow-moderate"]],
    blurb: "Pillowy pipe-organ polyps that thrive where other corals sulk — low light, low flow, bottom corners. If you have a 'dead zone' in your scape, a blasto colony is the answer. Undemanding and increasingly collectible." },
  { id: "l10", cat: "LPS", name: "Open Brain Coral", sci: "Trachyphyllia geoffroyi", wiki: "Trachyphyllia", diff: "Easy", g: ["#ff7a5c", "#3ce0a3"],
    facts: [["Light", "Low-Medium"], ["Flow", "Low"], ["Placement", "Sandbed only"], ["Feeding", "Weekly meaty foods"], ["Growth", "Slow inflation"]],
    blurb: "A single giant fleshy polyp that inflates like a neon waterbed. Belongs on the sand, never on rock — the flesh tears on hard edges. Feed it silversides or mysis weekly and it will inflate to twice its skeleton size." },
  { id: "l11", cat: "LPS", name: "Scoly", sci: "Homophyllia australis", wiki: "Homophyllia", diff: "Medium", g: ["#ff5d72", "#ffc24d"],
    facts: [["Light", "Low"], ["Flow", "Low"], ["Placement", "Sandbed"], ["Feeding", "Weekly, target"], ["Growth", "Very slow"]],
    blurb: "One polyp, one masterpiece — bullseye and warpaint morphs command four figures. Sandbed placement, gentle flow, weekly feeding. Buying tip: a scoly whose flesh fully covers its skeleton edge is healthy; receding edges spell trouble." },
  { id: "l12", cat: "LPS", name: "Plate Coral", sci: "Fungia", wiki: "Fungia", diff: "Easy", g: ["#ffc24d", "#ff9d8a"],
    facts: [["Light", "Medium"], ["Flow", "Low-Medium"], ["Placement", "Sandbed — it walks!"], ["Feeding", "Loves meaty food"], ["Growth", "Moderate"]],
    blurb: "A free-living disc that isn't attached to anything — and genuinely moves. Plates inflate, tilt, and scoot across the sand over days. Never wedge one into rockwork. Can regrow an entire animal from a fragment ('babies' from a dying plate are real)." },
  { id: "l13", cat: "LPS", name: "Bubble Coral", sci: "Plerogyra sinuosa", wiki: "Plerogyra sinuosa", diff: "Easy", g: ["#e9f7fc", "#3fe3ff"],
    facts: [["Light", "Low"], ["Flow", "Low"], ["Placement", "Low, protected"], ["Sweepers", "Long — give space"], ["Growth", "Slow"]],
    blurb: "Grape-like white bubbles by day, feeding tentacles by night. The bubbles are delicate — no strong flow, no fish that nip. An elegant old-school LPS that's regaining popularity in low-energy lagoon-style tanks." },

  /* ============================ SOFT ============================ */
  { id: "o1", cat: "Soft", name: "Toadstool Leather", sci: "Sarcophyton", wiki: "Sarcophyton", diff: "Easy", g: ["#ffc24d", "#84a8ba"],
    facts: [["Light", "Medium"], ["Flow", "Medium"], ["Placement", "Give it room — gets big"], ["Quirk", "Sheds a waxy film"], ["Growth", "Slow but huge"]],
    blurb: "The mushroom-cap centerpiece of softie tanks. Periodically closes up, looks dead, sheds a waxy layer, and reopens bigger — every new leather keeper panics the first time. Don't. Can reach dinner-plate size over years." },
  { id: "o2", cat: "Soft", name: "Devil's Hand Leather", sci: "Lobophytum", wiki: "Lobophytum", diff: "Easy", g: ["#ff9d8a", "#ffc24d"],
    facts: [["Light", "Medium"], ["Flow", "Medium"], ["Placement", "Mid"], ["Quirk", "Also sheds"], ["Growth", "Moderate"]],
    blurb: "Thick finger-like lobes reaching upward. Every bit as bulletproof as the toadstool with a more sculptural silhouette. Like all leathers it wages quiet chemical warfare (allelopathy) — run carbon in mixed tanks with SPS." },
  { id: "o3", cat: "Soft", name: "Kenya Tree", sci: "Capnella", wiki: "Capnella", diff: "Easy", g: ["#3ce0a3", "#84a8ba"],
    facts: [["Light", "Any"], ["Flow", "Any"], ["Placement", "Anywhere (it decides)"], ["Warning", "Spreads by dropping branches"], ["Growth", "Weed-tier"]],
    blurb: "A soft pink-tan tree that survives everything and reproduces by dropping branchlets that float off and colonize new rock. You don't keep Kenya trees; you negotiate with them. Great for beginners and nutrient-heavy tanks — just know what you're signing up for." },
  { id: "o4", cat: "Soft", name: "Green Star Polyps", sci: "Briareum", wiki: "Briareum", diff: "Easy", g: ["#3ce0a3", "#2ee6c8"],
    facts: [["Light", "Any"], ["Flow", "Medium"], ["Placement", "ISOLATED island or back wall"], ["Warning", "Invasive mat"], ["Growth", "Aggressive carpet"]],
    blurb: "A neon-green shag carpet that waves hypnotically — and annexes everything it touches. The pro move: give it its own island rock or the back wall, where its aggression becomes a feature. Never let it touch your main scape." },
  { id: "o5", cat: "Soft", name: "Pulsing Xenia", sci: "Xenia", wiki: "Xenia (genus)", diff: "Easy", g: ["#ff9d8a", "#e9f7fc"],
    facts: [["Light", "Medium"], ["Flow", "Low-Medium"], ["Placement", "Isolated island"], ["Quirk", "Rhythmic pulsing"], ["Growth", "Invasive when happy"]],
    blurb: "The only coral that visibly pumps — polyps open and close in a mesmerizing rhythm no one fully understands. Thrives in 'dirty' water where other corals struggle. Same containment policy as GSP: island only, or it will march across your tank." },
  { id: "o6", cat: "Soft", name: "Zoanthids", sci: "Zoanthus", wiki: "Zoanthus", diff: "Easy", g: ["#ff7a5c", "#b06cff"],
    facts: [["Light", "Medium"], ["Flow", "Medium"], ["Placement", "Anywhere"], ["SAFETY", "Palytoxin — wear gloves"], ["Growth", "Fast colonies"]],
    blurb: "Button polyps in infinite named morphs (Utter Chaos, Rastas, Sunny Ds) — the collectible card game of reefing. SAFETY: some zoas/palys contain palytoxin, one of the most toxic natural compounds known. Gloves and glasses when fragging, never boil rock with polyps. Respect them and they're wonderful." },
  { id: "o7", cat: "Soft", name: "Palythoa", sci: "Palythoa", wiki: "Palythoa", diff: "Easy", g: ["#84a8ba", "#3ce0a3"],
    facts: [["Light", "Any"], ["Flow", "Any"], ["Placement", "Anywhere"], ["SAFETY", "HIGH palytoxin risk"], ["Growth", "Fast, larger polyps"]],
    blurb: "Zoas' bigger, tougher cousins. Grandis palys have polyps the size of quarters. The palytoxin warning goes double here — Palythoa species carry the highest concentrations. Handle underwater, wash hands, never aerosolize (no power-washing rocks)." },
  { id: "o8", cat: "Soft", name: "Mushroom Coral", sci: "Discosoma", wiki: "Discosoma", diff: "Easy", g: ["#b06cff", "#ff5d72"],
    facts: [["Light", "Low"], ["Flow", "Low"], ["Placement", "Low, shaded fine"], ["Feeding", "None needed"], ["Growth", "Splits + wanders"]],
    blurb: "Colored discs that ask for nothing — the most forgiving coral in the hobby. They split when happy and occasionally detach to drift somewhere they like better. A shaded low-flow corner your other corals reject is mushroom paradise." },
  { id: "o9", cat: "Soft", name: "Ricordea", sci: "Ricordea florida", wiki: "Ricordea", diff: "Easy", g: ["#2ee6c8", "#ff7a5c"],
    facts: [["Light", "Low-Medium"], ["Flow", "Low"], ["Placement", "Low"], ["Feeding", "Optional"], ["Growth", "Slow splits"]],
    blurb: "Caribbean mushrooms covered in bubble-like bumps with the best color saturation per square inch in the hobby. Orange, teal, rainbow — collectors mount them in 'ricordea gardens.' Slower than discosoma but far flashier." },
  { id: "o10", cat: "Soft", name: "Bounce Mushroom", sci: "Rhodactis", wiki: "Rhodactis", diff: "Medium", g: ["#3fe3ff", "#b06cff"],
    facts: [["Light", "Low"], ["Flow", "Low"], ["Placement", "Low"], ["Value", "$$$ — the flex coral"], ["Growth", "Slow"]],
    blurb: "Rhodactis mushrooms that develop swollen, bubble-like vesicles — the 'bounce.' OG Bounces sparked a genuine gold rush. Care is standard mushroom-easy; the challenge is the price tag. Bubbles develop over time under stable, moderate conditions." },
  { id: "o11", cat: "Soft", name: "Finger Leather", sci: "Sinularia", wiki: "Sinularia", diff: "Easy", g: ["#84a8ba", "#3ce0a3"],
    facts: [["Light", "Medium"], ["Flow", "Medium"], ["Placement", "Mid"], ["Quirk", "Allelopathic"], ["Growth", "Steady"]],
    blurb: "Branching cream-to-green fingers that add movement and height to softie scapes. Among the hardiest corals kept. Runs the same chemical interference as other leathers — carbon is your friend in mixed reefs." },

  /* ============================ INVERTS ============================ */
  { id: "i1", cat: "Invert", name: "Skunk Cleaner Shrimp", sci: "Lysmata amboinensis", wiki: "Lysmata amboinensis", diff: "Easy", g: ["#ff9d8a", "#ffc24d"],
    facts: [["Max size", "2.5\""], ["Reef safe", "Yes"], ["Role", "Parasite cleaner"], ["Quirk", "Molts monthly"], ["Acclimation", "Drip slowly — sensitive"]],
    blurb: "Sets up a cleaning station and services your fish like a tiny car wash — genuinely removes parasites. Will also mug you for food during feeding. The empty 'dead shrimp' you'll find is a molt; the real one is hiding while its new shell hardens." },
  { id: "i2", cat: "Invert", name: "Blood Red Fire Shrimp", sci: "Lysmata debelius", wiki: "Lysmata debelius", diff: "Easy", g: ["#ff5d72", "#e9f7fc"],
    facts: [["Max size", "2\""], ["Reef safe", "Yes"], ["Role", "Cleaner (shy)"], ["Habitat", "Caves, overhangs"], ["Acclimation", "Drip slowly"]],
    blurb: "Deep crimson with white polka dots — the most beautiful shrimp in the hobby, and it knows it, which is why it hides in caves and only shows its antennae. Give it an overhang near the front glass if you actually want to see it." },
  { id: "i3", cat: "Invert", name: "Peppermint Shrimp", sci: "Lysmata wurdemanni", wiki: "Lysmata wurdemanni", diff: "Easy", g: ["#ff9d8a", "#ff7a5c"],
    facts: [["Max size", "2\""], ["Reef safe", "Mostly"], ["Role", "Eats Aiptasia!"], ["Caution", "May pick at LPS"], ["Buy", "True wurdemanni only"]],
    blurb: "The natural Aiptasia exterminator — a trio can clear an infested tank in weeks. Make sure you get true peppermints, not lookalike camel shrimp (which eat coral instead). Occasionally samples LPS flesh; most behave." },
  { id: "i4", cat: "Invert", name: "Sexy Shrimp", sci: "Thor amboinensis", wiki: "Thor amboinensis", diff: "Easy", g: ["#ffc24d", "#ff9d8a"],
    facts: [["Max size", "0.75\""], ["Reef safe", "Yes"], ["Keep", "Trios in nanos"], ["Quirk", "The dance"], ["Host", "Anemones, ricordea"]],
    blurb: "A thumbnail-size shrimp that constantly waves its abdomen in the air — the eponymous dance. Keep three in a nano perched on ricordea or an anemone. Big tanks swallow them; they're pico/nano royalty." },
  { id: "i5", cat: "Invert", name: "Coral Banded Shrimp", sci: "Stenopus hispidus", wiki: "Stenopus hispidus", diff: "Easy", g: ["#ff5d72", "#e9f7fc"],
    facts: [["Max size", "3\" + long arms"], ["Reef safe", "Yes*"], ["Caution", "May catch tiny fish/shrimp"], ["Keep", "Singly or mated pair"], ["Lifespan", "3-5 yrs"]],
    blurb: "Barber-pole banding and dramatic boxing-glove arms. Striking and mostly well-behaved, but big specimens have been known to ambush very small fish and other shrimp. One per tank unless you buy a bonded pair." },
  { id: "i6", cat: "Invert", name: "Tiger Pistol Shrimp", sci: "Alpheus bellulus", wiki: "Alpheus bellulus", diff: "Easy", g: ["#ffc24d", "#84a8ba"],
    facts: [["Max size", "2\""], ["Reef safe", "Yes"], ["Partner", "Watchman/shrimp gobies"], ["Quirk", "Snap = 218 dB bubble"], ["Habitat", "Digs constantly"]],
    blurb: "Nearly blind, armed with a claw that snaps a cavitation bubble louder than a gunshot, and permanently paired with a goby bodyguard. The clicking from your tank at night? That's him. The goby-pistol partnership is the best $40 show in reefing." },
  { id: "i7", cat: "Invert", name: "Emerald Crab", sci: "Mithraculus sculptus", wiki: "Mithraculus sculptus", diff: "Easy", g: ["#3ce0a3", "#84a8ba"],
    facts: [["Max size", "2\""], ["Reef safe", "Mostly"], ["Role", "Eats bubble algae"], ["Caution", "Big ones get bold"], ["Keep", "1 per 20 gal"]],
    blurb: "The bubble-algae specialist — one of few things that eats Valonia. Small emeralds are model citizens; large hungry ones occasionally pick at polyps or nap in your acans. Keep them fed and swap out any that grow too bold." },
  { id: "i8", cat: "Invert", name: "Blue-Leg Hermit", sci: "Clibanarius tricolor", wiki: "Clibanarius tricolor", diff: "Easy", g: ["#3fe3ff", "#ff9d8a"],
    facts: [["Max size", "1\""], ["Reef safe", "Yes*"], ["Role", "Detritus + algae"], ["Caution", "Kills snails for shells"], ["Tip", "Add empty shells"]],
    blurb: "Tiny janitors that flip through the sand and rockwork all day. Their one crime: evicting snails from their shells (fatally). Scatter empty shells of graduating sizes around the tank and your snail population will thank you." },
  { id: "i9", cat: "Invert", name: "Trochus Snail", sci: "Trochus", wiki: "Trochus", diff: "Easy", g: ["#84a8ba", "#3ce0a3"],
    facts: [["Max size", "1\""], ["Reef safe", "Yes"], ["Role", "Film algae, diatoms"], ["Superpower", "Self-rights when flipped"], ["Breeds", "In-tank, commonly"]],
    blurb: "The best all-around cleanup snail: eats film algae and diatoms, rights itself when knocked over (unlike astreas, which die stranded), and breeds readily in captivity — free cleanup crew. Buy trochus first, everything else second." },
  { id: "i10", cat: "Invert", name: "Turbo Snail", sci: "Turbo (gastropod)", wiki: "Turbo (gastropod)", diff: "Easy", g: ["#84a8ba", "#ffc24d"],
    facts: [["Max size", "2\""], ["Reef safe", "Yes (clumsy)"], ["Role", "Hair algae bulldozer"], ["Caution", "Knocks over frags"], ["Note", "Mexican turbos run cooler"]],
    blurb: "An algae-eating bulldozer that mows hair algae like nothing else — and rearranges any frag that isn't glued down. A few go a long way. Mexican turbos prefer cooler water and can fade in warm tanks long-term." },
  { id: "i11", cat: "Invert", name: "Nassarius Snail", sci: "Nassarius", wiki: "Nassarius", diff: "Easy", g: ["#84a8ba", "#ff9d8a"],
    facts: [["Max size", "0.75\""], ["Reef safe", "Yes"], ["Role", "Sand bed / leftover food"], ["Quirk", "Periscope siphon"], ["Habitat", "Buried until feeding time"]],
    blurb: "Lives buried with a periscope siphon poking up — then erupts from the sand like a tiny zombie the second food hits the water. Keeps sand beds stirred and leftovers cleaned. The feeding-time eruption never gets old." },
  { id: "i12", cat: "Invert", name: "Fighting Conch", sci: "Strombus alatus", wiki: "Strombus alatus", diff: "Easy", g: ["#ffc24d", "#84a8ba"],
    facts: [["Max size", "3.5\""], ["Reef safe", "Yes"], ["Role", "Sand bed janitor"], ["Misnomer", "Fights nothing"], ["Needs", "Sand bed + open floor"]],
    blurb: "Despite the name, it fights nothing — it hops. A googly-eyed sand vacuum that keeps the bed white and aerated. One per couple square feet of open sand; they'll starve in rock-packed tanks." },
  { id: "i13", cat: "Invert", name: "Tuxedo Urchin", sci: "Mespilia globulus", wiki: "Mespilia globulus", diff: "Easy", g: ["#b06cff", "#3f9bff"],
    facts: [["Max size", "3\""], ["Reef safe", "Yes*"], ["Role", "Algae mower"], ["Quirk", "Wears hats"], ["Caution", "Bulldozes loose frags"]],
    blurb: "Blue-and-red bands and a habit of picking up frag plugs, shells, and small equipment to wear as camouflage hats. Superb algae grazer including some turf algae. Glue your frags down — it's not malicious, just oblivious." },
  { id: "i14", cat: "Invert", name: "Maxima Clam", sci: "Tridacna maxima", wiki: "Maxima clam", diff: "Hard", g: ["#3fe3ff", "#b06cff"],
    facts: [["Max size", "12\""], ["Light", "Very high (SPS-level)"], ["Placement", "Rockwork, upper half"], ["Needs", "Stable Ca/alk, mature tank"], ["Watch", "Pyramid snails"]],
    blurb: "Electric-blue mantle patterns that photograph like a galaxy. Effectively photosynthetic — needs SPS-tier light and stable calcium/alkalinity (it's building that shell). Inspect for rice-grain pyramid snails at the byssus and mantle edge; a melanurus wrasse handles them." },
  { id: "i15", cat: "Invert", name: "Bubble Tip Anemone", sci: "Entacmaea quadricolor", wiki: "Bubble-tip anemone", diff: "Medium", g: ["#ff5d72", "#3ce0a3"],
    facts: [["Size", "6-12\""], ["Light", "High"], ["Placement", "It decides — foot in rock"], ["Clown host", "Yes — the classic"], ["Caution", "Wanders; guard powerheads"]],
    blurb: "The classic clownfish host. Rose, green, and rainbow BTAs split readily in captivity — always buy aquacultured. The catch: anemones walk. They wander until happy, stinging corals en route, and love powerhead intakes (use guards). Add only to tanks 6+ months old." },

  /* ============================ PESTS ============================ */
  { id: "p1", cat: "Pest", name: "Aiptasia", sci: "Aiptasia", wiki: "Aiptasia", diff: "Pest", g: ["#84a8ba", "#3ce0a3"],
    facts: [["Threat", "Stings corals, spreads fast"], ["Arrives via", "Live rock, frag plugs"], ["Fix (natural)", "Peppermint shrimp, filefish"], ["Fix (chemical)", "Aiptasia-X, kalk paste"], ["Never", "Squish it — it multiplies"]],
    blurb: "The glass anemone — the hobby's most famous pest. Every fragment left behind regrows, so mechanical removal backfires spectacularly. Inject or smother with Aiptasia-X/kalk paste, or deploy peppermint shrimp. Dip every frag before it enters your tank; that's how it got in." },
  { id: "p2", cat: "Pest", name: "Dinoflagellates", sci: "Dinoflagellata", wiki: "Dinoflagellate", diff: "Pest", g: ["#ffc24d", "#84a8ba"],
    facts: [["Looks like", "Snotty brown strings w/ bubbles"], ["Cause", "Nutrients at ZERO"], ["Fix", "Raise NO3/PO4, UV, blackouts"], ["Danger", "Some strains are toxic"], ["Confirm", "Microscope — $20 well spent"]],
    blurb: "The nightmare bloom that strikes ultra-clean tanks — dinos exploit a nutrient vacuum when NO3/PO4 hit zero. Counterintuitive cure: dirty your water up (dose nitrate/phosphate, feed heavy), run UV, siphon daily. Ostreopsis strains are toxic to snails and can irritate humans. A cheap microscope confirms which strain you're fighting." },
  { id: "p3", cat: "Pest", name: "Green Hair Algae", sci: "Derbesia", wiki: "Green algae", diff: "Pest", g: ["#3ce0a3", "#84a8ba"],
    facts: [["Cause", "Excess PO4/NO3 + light"], ["Fix", "Manual removal + nutrient control"], ["Crew", "Turbos, urchins, tangs, lawnmower"], ["Check", "Old bulbs, RODI TDS"], ["Timeline", "Weeks, not days"]],
    blurb: "The rite of passage. GHA blooms on excess nutrients — check your RODI (TDS should read 0), cut feeding, and pull what you can by hand before the cleanup crew mops up the rest. It always looks worse before it gets better; consistency wins in 3-6 weeks." },
  { id: "p4", cat: "Pest", name: "Bubble Algae", sci: "Valonia ventricosa", wiki: "Valonia ventricosa", diff: "Pest", g: ["#3ce0a3", "#2ee6c8"],
    facts: [["Looks like", "Green marbles"], ["Spreads", "When popped (spores)"], ["Fix", "Remove whole, siphon out"], ["Crew", "Emerald crabs love it"], ["Prevention", "Inspect frag plugs"]],
    blurb: "Shiny green marbles that are weirdly beautiful and infuriatingly persistent. Popping one in-tank releases spores — remove bubbles whole, ideally siphoning as you pry. Emerald crabs are the biological answer. Comes in on frag plugs; scrub or replace them." },
  { id: "p5", cat: "Pest", name: "Bryopsis", sci: "Bryopsis", wiki: "Bryopsis", diff: "Pest", g: ["#3ce0a3", "#3f9bff"],
    facts: [["Looks like", "Feathery ferns (not GHA)"], ["Ignores", "Normal nutrient control"], ["Fix", "Fluconazole (Reef Flux)"], ["Crew", "Almost nothing eats it"], ["ID matters", "Ferns = bryopsis"]],
    blurb: "Hair algae's evil twin — feathery, fern-like fronds that laugh at cleanup crews and nutrient control. The good news: fluconazole (Reef Flux) melts it specifically, a genuine silver bullet. Look closely at your 'GHA' — if the strands branch like ferns, treat for bryopsis instead." },
  { id: "p6", cat: "Pest", name: "Vermetid Snails", sci: "Vermetidae", wiki: "Vermetidae", diff: "Pest", g: ["#84a8ba", "#ff9d8a"],
    facts: [["Looks like", "Tiny tubes + mucus webs"], ["Threat", "Webs irritate corals"], ["Fix", "Superglue the tube openings"], ["Crew", "Bumblebee snails (partial)"], ["Reality", "Management, not eradication"]],
    blurb: "Tiny calcified tubes cemented to rock that cast mucus fishing nets — harmless in small numbers, coral-irritating in bulk. Dab superglue over each tube opening to entomb them. Full eradication is rare; population control is the realistic goal." },
  { id: "p7", cat: "Pest", name: "Marine Ich", sci: "Cryptocaryon irritans", wiki: "Cryptocaryon", diff: "Pest", g: ["#e9f7fc", "#84a8ba"],
    facts: [["Looks like", "Salt grains on fins/body"], ["Cycle", "~2 wks; spots come & go"], ["Fix", "Copper or TTM in QT"], ["Tank fallow", "76+ days to starve it"], ["Prevention", "QT everything"]],
    blurb: "White salt-grain spots that vanish and return as the parasite cycles — the disappearing act fools keepers into thinking it's cured. Reef-safe 'treatments' don't eradicate it; copper or tank-transfer method in quarantine does. Managing it long-term means low stress and great nutrition. QT is cheaper than the alternative." },
  { id: "p8", cat: "Pest", name: "Marine Velvet", sci: "Amyloodinium ocellatum", wiki: "Amyloodinium ocellatum", diff: "Pest", g: ["#ffc24d", "#84a8ba"],
    facts: [["Looks like", "Gold dust, rapid breathing"], ["Speed", "Kills in 24-72 hrs"], ["Fix", "Copper immediately, in QT"], ["Vs ich", "Finer dust, much faster"], ["Prevention", "QT with observation"]],
    blurb: "The killer. A fine gold dusting, heavy breathing, and glass-surfing — then dead fish within days. Velvet moves catastrophically faster than ich; by the time it's obvious, hours matter. Copper in a hospital tank immediately. This disease alone justifies quarantining every fish you buy." },
  { id: "p9", cat: "Pest", name: "Red Planaria Flatworms", sci: "Convolutriloba", wiki: "Flatworm", diff: "Pest", g: ["#ff5d72", "#ff9d8a"],
    facts: [["Looks like", "Rust-red confetti on rock"], ["Threat", "Smothers corals in numbers"], ["Fix", "Flatworm eXit + heavy siphon"], ["Warning", "Dead worms release toxin"], ["Crew", "Melanurus wrasse, blue velvet nudi"]],
    blurb: "Rust-colored confetti that multiplies into a smothering carpet. Treating with Flatworm eXit works but the die-off releases toxins — siphon out as many as possible BEFORE dosing, run carbon after, and have water ready for a change. A melanurus wrasse keeps stragglers in check." },
  { id: "p10", cat: "Pest", name: "Asterina Starfish", sci: "Asterina", wiki: "Asterina", diff: "Pest", g: ["#84a8ba", "#e9f7fc"],
    facts: [["Looks like", "Tiny lopsided stars"], ["Verdict", "Mostly harmless"], ["Some", "Nip zoas/coralline"], ["Fix if needed", "Harlequin shrimp"], ["Population", "Tracks nutrients"]],
    blurb: "Tiny asymmetric stars that show up uninvited and divide by tearing themselves in half. The eternal debate: most graze harmlessly on film algae, but some strains develop a taste for zoas. If yours behave, ignore them. If not, a harlequin shrimp eats nothing else." },

  /* ============================ FISH (added) ============================ */
  { id: "f21", cat: "Fish", name: "Blue Green Chromis", sci: "Chromis viridis", wiki: "Chromis viridis", diff: "Easy", g: ["#3ce0a3", "#3f9bff"],
    facts: [["Max size", "3\""], ["Min tank", "30 gal"], ["Diet", "Omnivore — flake, frozen"], ["Reef safe", "Yes"], ["Temperament", "Peaceful; keep in odd-numbered groups"]],
    blurb: "The quintessential schooling reef fish — iridescent green-blue that shimmers as a group moves in unison. Keep 5-7 and add them all at once to reduce pecking-order losses. Bulletproof, cheap, and a 'dither fish' that coaxes shy tankmates out of the rocks." },
  { id: "f22", cat: "Fish", name: "Neon Goby", sci: "Elacatinus oceanops", wiki: "Elacatinus oceanops", diff: "Easy", g: ["#3fe3ff", "#0d2620"],
    facts: [["Max size", "2\""], ["Min tank", "10 gal"], ["Diet", "Carnivore — small frozen"], ["Reef safe", "Yes"], ["Temperament", "Peaceful; a cleaner"]],
    blurb: "A tiny electric-blue-striped bottom-dweller that sets up cleaning stations and picks parasites off larger fish. Captive-bred everywhere, perfect for nanos, and an outstanding tankmate for clowns and firefish. One of the few gobies that'll breed in a home tank." },
  { id: "f23", cat: "Fish", name: "Yellowtail Blue Damsel", sci: "Chrysiptera parasema", wiki: "Chrysiptera parasema", diff: "Easy", g: ["#3f6fd6", "#ffd84d"],
    facts: [["Max size", "2.5\""], ["Min tank", "30 gal"], ["Diet", "Omnivore"], ["Reef safe", "Yes"], ["Temperament", "Semi-aggressive"]],
    blurb: "Electric blue body, yellow tail, and tough as nails — one of the hardiest fish in the hobby. The catch is attitude: damsels get territorial as they mature. Add last, give hiding spots, and it's a vivid splash of color that shrugs off beginner mistakes." },
  { id: "f24", cat: "Fish", name: "Yellow Coris Wrasse", sci: "Halichoeres chrysus", wiki: "Halichoeres chrysus", diff: "Easy", g: ["#ffd84d", "#ff9d3a"],
    facts: [["Max size", "5\""], ["Min tank", "50 gal"], ["Diet", "Carnivore — pests, pods"], ["Reef safe", "Yes"], ["Temperament", "Peaceful; active"]],
    blurb: "Canary-yellow and always in motion, this wrasse eats fireworms, pyramid snails, and parasites — beauty and pest control in one. Needs a 2\"+ sand bed to bury itself at night. A tight lid is essential; all Halichoeres wrasses are jumpers." },
  { id: "f25", cat: "Fish", name: "Court Jester Goby", sci: "Koumansetta rainfordi", wiki: "Koumansetta rainfordi", diff: "Medium", g: ["#3ce0a3", "#ff7a00"],
    facts: [["Max size", "3\""], ["Min tank", "20 gal mature"], ["Diet", "Grazer — film algae, pods"], ["Reef safe", "Yes"], ["Temperament", "Peaceful"]],
    blurb: "Green and orange racing stripes on a tiny sand-sifting body. Grazes film algae and detritus, but needs a mature tank with established microfauna or supplemental feeding — they can thin out in spotless setups. A gorgeous nano janitor." },
  { id: "f26", cat: "Fish", name: "Chalk Bass", sci: "Serranus tortugarum", wiki: "Serranus tortugarum", diff: "Easy", g: ["#b06cff", "#ffb03a"],
    facts: [["Max size", "3\""], ["Min tank", "30 gal"], ["Diet", "Carnivore"], ["Reef safe", "Yes"], ["Temperament", "Peaceful; group if added together"]],
    blurb: "Lavender-and-gold and criminally underrated — one of the hardiest reef fish available. Reef safe, peaceful, and can be kept in small groups if introduced simultaneously. A bulletproof choice that adds unusual color low in the water column." },
  { id: "f27", cat: "Fish", name: "Bicolor Blenny", sci: "Ecsenius bicolor", wiki: "Ecsenius bicolor", diff: "Easy", g: ["#3f6fd6", "#ff7a00"],
    facts: [["Max size", "4\""], ["Min tank", "30 gal"], ["Diet", "Herbivore lean — algae, pellets"], ["Reef safe", "Yes"], ["Temperament", "Peaceful; one blenny per tank"]],
    blurb: "Blue front, orange back, and endless personality perched on the rockwork. Grazes film algae and needs some greens in its diet. Occasionally nips at clam mantles or LPS if underfed, but mostly a model citizen with a great face." },
  { id: "f28", cat: "Fish", name: "Neon Dottyback", sci: "Pseudochromis aldabraensis", wiki: "Pseudochromis aldabraensis", diff: "Easy", g: ["#ff7a00", "#3f9bff"],
    facts: [["Max size", "4\""], ["Min tank", "30 gal"], ["Diet", "Carnivore"], ["Reef safe", "Yes"], ["Temperament", "Aggressive"]],
    blurb: "A blazing neon-orange bullet of energy that also helps control bristleworm populations. Captive-bred and hardy — but feisty. Add it last, since it'll defend its territory against newcomers. Worth it for the color and constant activity." },
  { id: "f29", cat: "Fish", name: "Foxface Rabbitfish", sci: "Siganus vulpinus", wiki: "Siganus vulpinus", diff: "Medium", g: ["#ffd84d", "#e9f7fc"],
    facts: [["Max size", "9\""], ["Min tank", "75 gal"], ["Diet", "Herbivore — heavy greens"], ["Reef safe", "Yes"], ["CAUTION", "Venomous dorsal spines"]],
    blurb: "A bright yellow algae-eating machine with a striking face mask — and venomous dorsal spines, so handle with care (the sting is like a bee's, but worse). Superb at mowing hair algae. Generally reef safe, occasionally samples LPS. Keep only one per tank." },
  { id: "f30", cat: "Fish", name: "Clarkii Clownfish", sci: "Amphiprion clarkii", wiki: "Amphiprion clarkii", diff: "Easy", g: ["#ff7a00", "#0d2620"],
    facts: [["Max size", "5\""], ["Min tank", "30 gal"], ["Diet", "Omnivore"], ["Reef safe", "Yes"], ["Temperament", "Semi-aggressive"]],
    blurb: "The hardiest, boldest clownfish — black body banded in white with yellow fins. More aggressive than ocellaris and will host almost any anemone. A great choice if you want clownfish personality with extra toughness and a different look." },
  { id: "f31", cat: "Fish", name: "Engineer Goby", sci: "Pholidichthys leucotaenia", wiki: "Pholidichthys leucotaenia", diff: "Easy", g: ["#0d2620", "#e9f7fc"],
    facts: [["Max size", "12\""], ["Min tank", "55 gal"], ["Diet", "Carnivore"], ["Reef safe", "Yes"], ["Quirk", "Constant burrowing"]],
    blurb: "An eel-like tunneling machine that rearranges your sand bed into an underground city — endlessly entertaining. Juveniles are black with a white stripe (mimicking catfish); adults develop convict-like barring. Harmless to corals, though its digging can topple loose rock." },
  { id: "f32", cat: "Fish", name: "Yellow Watchman + Pistol Pair", sci: "Cryptocentrus cinctus", wiki: "Cryptocentrus cinctus", diff: "Easy", g: ["#ffd84d", "#84a8ba"],
    facts: [["Max size", "4\""], ["Min tank", "20 gal"], ["Diet", "Carnivore — sinking food"], ["Reef safe", "Yes"], ["Best with", "A tiger pistol shrimp"]],
    blurb: "Already have the watchman goby entry? This is the symbiotic pairing spelled out: the near-blind pistol shrimp digs and maintains a shared burrow while the goby stands guard at the entrance. The single best behavioral display in the nano hobby." },

  /* ============================ LPS (added) ============================ */
  { id: "l14", cat: "LPS", name: "Elegance Coral", sci: "Catalaphyllia jardinei", wiki: "Catalaphyllia", diff: "Medium", g: ["#3ce0a3", "#b06cff"],
    facts: [["Light", "Low-Medium"], ["Flow", "Low"], ["Placement", "Sandbed only"], ["Feeding", "Loves meaty foods"], ["Watch for", "Elegance Coral Syndrome"]],
    blurb: "Flowing anemone-like tentacles with purple tips — a genuine showpiece. Belongs on the sand, never on rock. Historically plagued by 'Elegance Coral Syndrome,' but aquacultured and Australian specimens are far hardier now. Feed it well and it's spectacular." },
  { id: "l15", cat: "LPS", name: "Sun Coral", sci: "Tubastraea", wiki: "Tubastraea", diff: "Hard", g: ["#ff7a00", "#ffd84d"],
    facts: [["Light", "None needed (non-photosynthetic)"], ["Flow", "Medium"], ["Placement", "Shaded overhang"], ["Feeding", "MUST feed every polyp, 2-4x/week"], ["Reward", "Blazing orange bloom"]],
    blurb: "A non-photosynthetic stunner — brilliant orange polyps on a dark skeleton. The catch is the commitment: it doesn't photosynthesize, so every polyp must be individually target-fed several times a week or it starves. For dedicated keepers, few corals are more rewarding." },
  { id: "l16", cat: "LPS", name: "Goniopora (Flowerpot)", sci: "Goniopora", wiki: "Goniopora", diff: "Medium", g: ["#ff9d8a", "#3ce0a3"],
    facts: [["Light", "Medium"], ["Flow", "Low-Medium"], ["Placement", "Sandbed to low rock"], ["Feeding", "Benefits from fine foods"], ["Note", "Aquacultured = far hardier"]],
    blurb: "A bouquet of long daisy-like polyps that sway constantly — one of the most hypnotic corals in the hobby. Once had a terrible survival reputation, but modern aquacultured and Australian 'gonis' are genuinely hardy. Give it stable parameters and gentle flow." },
  { id: "l17", cat: "LPS", name: "Galaxea", sci: "Galaxea fascicularis", wiki: "Galaxea", diff: "Easy", g: ["#e9f7fc", "#3fe3ff"],
    facts: [["Light", "Medium"], ["Flow", "Medium"], ["Placement", "Give WIDE berth"], ["Sweepers", "Extremely long & aggressive"], ["Growth", "Fast"]],
    blurb: "Star-like polyps that look delicate and behave like a chainsaw — Galaxea has some of the longest, most aggressive sweeper tentacles in the hobby, reaching several inches to sting anything nearby. Beautiful and hardy, but quarantine it in its own corner of the tank." },
  { id: "l18", cat: "LPS", name: "Lobophyllia (Brain)", sci: "Lobophyllia", wiki: "Lobophyllia", diff: "Easy", g: ["#ff5d72", "#3ce0a3"],
    facts: [["Light", "Low-Medium"], ["Flow", "Low"], ["Placement", "Sandbed to low rock"], ["Feeding", "Weekly meaty foods"], ["Growth", "Slow"]],
    blurb: "Big, fleshy folded-brain colonies in outrageous color combos. Hardy and forgiving, with a huge appetite — target feed it and watch it swell. A close cousin of the acan and just as collectible, but in a massive single-colony form." },
  { id: "l19", cat: "LPS", name: "Pearl Bubble Coral", sci: "Physogyra", wiki: "Physogyra", diff: "Easy", g: ["#e9f7fc", "#84a8ba"],
    facts: [["Light", "Low"], ["Flow", "Low"], ["Placement", "Low, protected"], ["Sweepers", "Yes at night"], ["Growth", "Slow"]],
    blurb: "Smaller pearly bubbles than the classic bubble coral, packed densely across the colony. Delicate — no strong flow, no nippy fish. An elegant, glowing addition to a low-energy lagoon-style reef." },

  /* ============================ SOFT (added) ============================ */
  { id: "o12", cat: "Soft", name: "Clove Polyps", sci: "Clavularia", wiki: "Clavularia", diff: "Easy", g: ["#3ce0a3", "#2ee6c8"],
    facts: [["Light", "Medium"], ["Flow", "Medium"], ["Placement", "Rock; can spread"], ["Feeding", "None needed"], ["Growth", "Fast"]],
    blurb: "Feathery eight-tentacled star polyps in green, gold, and 'Daisy' varieties. Hardy and fast, they carpet rockwork with delicate motion. Like GSP, they can spread — give them their own zone. The ORA 'Green Clove' is a popular bright variant." },
  { id: "o13", cat: "Soft", name: "Neon Green Sinularia", sci: "Sinularia", wiki: "Sinularia", diff: "Easy", g: ["#3ce0a3", "#7dffb0"],
    facts: [["Light", "Medium"], ["Flow", "Medium-High"], ["Placement", "Mid"], ["Feeding", "Optional"], ["Growth", "Moderate"]],
    blurb: "An ORA-bred finger leather with an intense fluorescent green base and thick sculptural stalks. As hardy as any leather, it glows hard under actinics. Runs the usual leather allelopathy, so keep carbon going in a mixed reef." },
  { id: "o14", cat: "Soft", name: "Colt Coral", sci: "Cladiella", wiki: "Cladiella", diff: "Easy", g: ["#84a8ba", "#e9f7fc"],
    facts: [["Light", "Medium"], ["Flow", "Medium"], ["Placement", "Mid"], ["Quirk", "Sheds waxy film"], ["Growth", "Fast"]],
    blurb: "Soft, chunky branching arms in pale grey-green — sometimes called 'cauliflower' or 'finger' leather. Extremely hardy and fast-growing, a great early softie. Sheds a waxy coat periodically like other leathers; run carbon and don't panic." },
  { id: "o15", cat: "Soft", name: "Yellow Polyps", sci: "Parazoanthus", wiki: "Parazoanthus", diff: "Easy", g: ["#ffd84d", "#ffe98a"],
    facts: [["Light", "Medium"], ["Flow", "Medium"], ["Placement", "Rock"], ["Feeding", "Benefits from small foods"], ["Growth", "Moderate"]],
    blurb: "Bright golden-yellow polyps that dot the rockwork like little suns. Hardy and easy, they multiply steadily to form cheerful colonies. Yellow is a rare color in soft corals, which makes these a nice, affordable pop of it." },
  { id: "o16", cat: "Soft", name: "Anthelia", sci: "Anthelia", wiki: "Anthelia", diff: "Easy", g: ["#84a8ba", "#3ce0a3"],
    facts: [["Light", "Medium"], ["Flow", "Low-Medium"], ["Placement", "Isolated — spreads"], ["Feeding", "None needed"], ["Growth", "Invasive"]],
    blurb: "Waving hand-like polyps often confused with Xenia, but Anthelia doesn't pulse — it just spreads. Hardy in dirty water and great for nutrient export, but it will march across the tank. Island placement only, same as Xenia and GSP." },

  /* ============================ INVERTS (added) ============================ */
  { id: "i16", cat: "Invert", name: "Rock Flower Anemone", sci: "Phymanthus crucifer", wiki: "Phymanthus crucifer", diff: "Easy", g: ["#ff5d72", "#3ce0a3"],
    facts: [["Size", "3-4\""], ["Light", "Medium"], ["Flow", "Low-Medium"], ["Placement", "Rock crevice; stays put"], ["Reef safe", "Yes"]],
    blurb: "The best anemone for reefers who fear anemones — rock flowers stay put in a crevice instead of wandering into powerheads. They come in wild color morphs, tolerate a range of conditions, and can be kept in gardens of many. A far safer choice than a BTA." },
  { id: "i17", cat: "Invert", name: "Pom Pom Crab", sci: "Lybia edmondsoni", wiki: "Lybia", diff: "Easy", g: ["#ff9d8a", "#e9f7fc"],
    facts: [["Size", "0.5\""], ["Reef safe", "Yes"], ["Quirk", "Carries anemones as pom-poms"], ["Placement", "Nano-friendly"], ["Diet", "Detritus, leftovers"]],
    blurb: "A thumbnail-sized crab that carries a tiny anemone in each claw and waves them like cheerleader pom-poms — for defense and feeding. Utterly charming, reef safe, and perfect for nanos. One of the hobby's great 'wait, what is THAT' animals." },
  { id: "i18", cat: "Invert", name: "Scarlet Reef Hermit", sci: "Paguristes cadenati", wiki: "Paguristes cadenati", diff: "Easy", g: ["#e8465e", "#ffd84d"],
    facts: [["Size", "1.5\""], ["Reef safe", "Yes"], ["Role", "Hair & film algae"], ["Vs blue-legs", "Far more peaceful"], ["Tip", "Add empty shells"]],
    blurb: "Bright red legs, yellow eyes, and a much better temperament than blue-leg hermits — scarlets rarely bother snails. Excellent grazers of hair and film algae. A touch pricier than blue-legs, but worth it for the peace of mind and the color." },
  { id: "i19", cat: "Invert", name: "Feather Duster Worm", sci: "Sabellastarte", wiki: "Sabellastarte", diff: "Easy", g: ["#ff9d8a", "#84a8ba"],
    facts: [["Size", "Crown to 4\""], ["Reef safe", "Yes"], ["Diet", "Filter feeder — phyto"], ["Placement", "Rock/sand crevice"], ["Quirk", "Retracts when startled"]],
    blurb: "A living feather crown that unfurls from a leathery tube to filter the water — pure elegant movement. Reef safe and peaceful; benefits from phytoplankton dosing since it feeds on tiny particles. It'll retract in a flash if a shadow passes over." },
  { id: "i20", cat: "Invert", name: "Harlequin Shrimp", sci: "Hymenocera picta", wiki: "Hymenocera picta", diff: "Medium", g: ["#ff7a9e", "#3f9bff"],
    facts: [["Size", "2\""], ["Reef safe", "Yes"], ["Diet", "ONLY starfish (incl. Asterina)"], ["Keep", "Singly or as a pair"], ["Use", "Asterina control"]],
    blurb: "One of the most beautiful animals in the hobby — cream, pink, and blue like spilled paint — with a bizarre catch: it eats nothing but starfish. Reefers use them to clear Asterina outbreaks, but you must keep a supply of stars, or feed chocolate-chip stars, or it starves." },
  { id: "i21", cat: "Invert", name: "Cerith Snail", sci: "Cerithium", wiki: "Cerithium", diff: "Easy", g: ["#84a8ba", "#3ce0a3"],
    facts: [["Size", "1\""], ["Reef safe", "Yes"], ["Role", "Sand & glass, detritus"], ["Bonus", "Burrows & aerates sand"], ["Breeds", "In-tank"]],
    blurb: "An unsung cleanup hero: ceriths work the sand bed and glass, eat detritus and algae, aerate the substrate by burrowing, and often breed in the tank. Nocturnal and tireless. Every cleanup crew should include a handful." },
];
