// Zoa & Paly morph guide.
//
// NOTE ON IMAGERY: named zoa morphs are hobbyist trade names, not species — there are no
// freely-licensed photos of "Utter Chaos" or "Rastas" the way there are for Amphiprion ocellaris.
// Every real photo of a named morph is a copyrighted vendor/hobbyist shot. So instead of faking
// photos, each morph carries its actual color signature (skirt / ring / mouth / center), which is
// exactly what reefers use to identify one, and the app renders an accurate polyp diagram from it.
//
// tier: rough market position — Starter (cheap, everywhere) → Grail (four figures, waiting lists)

export const ZOA_TIERS = ["All", "Starter", "Mid", "High-End", "Grail"];

export const ZOAS = [
  /* ---------- STARTER: bulletproof, cheap, fast growers ---------- */
  { id: "z1", name: "Green Bay Packers", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#ffd84d", mouth: "#ffe98a", center: "#2ee6c8",
    note: "Green skirt, yellow-gold center. The classic beginner zoa — nearly unkillable and multiplies like it's being paid to." },
  { id: "z2", name: "Radioactive Dragon Eye", tier: "Starter", growth: "Fast", polyp: "Large",
    skirt: "#3ce0a3", ring: "#ff7a00", mouth: "#ffd84d", center: "#ff5d00",
    note: "Neon green skirt with a blazing orange eye. One of the most recognizable zoas in the hobby and a rocket-fast grower." },
  { id: "z3", name: "Eagle Eye", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#2e8f6f", ring: "#1a3d2e", mouth: "#3ce0a3", center: "#0d2620",
    note: "Deep green with a dark, hawk-like center ring. Old-school, cheap, and grows in dense mats. A great filler between fancier colonies." },
  { id: "z4", name: "Fire and Ice", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#3fe3ff", ring: "#ff7a5c", mouth: "#ffd84d", center: "#ff5d72",
    note: "Icy blue skirt against a fiery orange center — the contrast is the whole point. Hardy and forgiving of nutrient swings." },
  { id: "z5", name: "Sunny D", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#ffb03a", ring: "#ff7a00", mouth: "#ffe98a", center: "#ffc24d",
    note: "Pure orange-gold sunburst. Cheap, cheerful, and grows fast enough to be a gateway drug into zoa collecting." },
  { id: "z6", name: "Green Hornet", tier: "Starter", growth: "Fast", polyp: "Large",
    skirt: "#3ce0a3", ring: "#0d2620", mouth: "#ffd84d", center: "#1a5c3a",
    note: "Big green polyps with a dark ring. Grows into a lawn if you let it — great for covering a rock fast." },
  { id: "z7", name: "Blue Hornet", tier: "Starter", growth: "Moderate", polyp: "Medium",
    skirt: "#3f9bff", ring: "#0d2040", mouth: "#3ce0a3", center: "#1a4a8f",
    note: "Blue skirt with green mouth. Colors pop hard under heavy actinics — a budget way to get blue into a colony." },
  { id: "z8", name: "Purple Death", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#8f5cd6", ring: "#3ce0a3", mouth: "#ffd84d", center: "#5a2e9e",
    note: "Purple skirt, green ring. Despite the metal name it's one of the most beginner-friendly zoas out there." },
  { id: "z9", name: "Armor of God", tier: "Starter", growth: "Moderate", polyp: "Medium",
    skirt: "#ffb03a", ring: "#6e3fbf", mouth: "#ffe98a", center: "#ff7a00",
    note: "Gold skirt with a purple ring. A staple in mixed colonies and reliably available at swaps." },
  { id: "z10", name: "Watermelon", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#ff5d72", mouth: "#ffb0c4", center: "#e8465e",
    note: "Green rim, pink-red flesh — reads exactly like the fruit. Fast, cheap, and a good confidence builder." },

  /* ---------- MID: the collector's bread and butter ---------- */
  { id: "z11", name: "Rastas", tier: "Mid", growth: "Fast", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#e8465e", mouth: "#ffd84d", center: "#ff7a00",
    note: "Green skirt, red ring, yellow mouth — the reggae colors that named it. Grows fast enough to fund a habit, which is why it's in every frag tank." },
  { id: "z12", name: "Utter Chaos", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#8f5cd6", ring: "#ff7a00", mouth: "#ffd84d", center: "#e8465e",
    note: "Purple skirt with a chaotic orange-red center that never looks the same twice. One of the most traded morphs in the hobby and a swap-table staple." },
  { id: "z13", name: "Bam Bam", tier: "Mid", growth: "Moderate", polyp: "Large",
    skirt: "#ff7a5c", ring: "#3ce0a3", mouth: "#ffe98a", center: "#ff5d00",
    note: "Orange skirt with a green ring and big fat polyps. A workhorse mid-tier zoa that colors up hard under blues." },
  { id: "z14", name: "Sunny Delight", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#ffd84d", ring: "#ff7a00", mouth: "#fff4c4", center: "#ffb03a",
    note: "A brighter, cleaner take on the orange sunburst. Slightly slower than Sunny D but noticeably more saturated." },
  { id: "z15", name: "Blue Agave", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#5cc8ff", ring: "#3ce0a3", mouth: "#ffd84d", center: "#2e9ed6",
    note: "Pale blue skirt with a green-gold center. Blues are rare in zoas, which is why this one holds its value." },
  { id: "z16", name: "Whammin' Watermelon", tier: "Mid", growth: "Moderate", polyp: "Large",
    skirt: "#3ce0a3", ring: "#e8465e", mouth: "#ffb0c4", center: "#ff5d72",
    note: "The upgraded watermelon — bigger polyps, deeper red, sharper green rim. Worth the step up from the basic version." },
  { id: "z17", name: "People Eater", tier: "Mid", growth: "Moderate", polyp: "Large",
    skirt: "#8f5cd6", ring: "#ffd84d", mouth: "#ff7a00", center: "#6e3fbf",
    note: "Purple skirt, gold ring, orange mouth. Big showy polyps that anchor a mixed zoa garden." },
  { id: "z18", name: "Nuclear Green", tier: "Mid", growth: "Fast", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#7dffb0", mouth: "#c4ffdc", center: "#2ee6c8",
    note: "Absurdly bright green all the way through. Under actinics it looks like it's plugged into a wall socket." },
  { id: "z19", name: "Gorilla Nipple", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#e8465e", ring: "#ffd84d", mouth: "#ff7a00", center: "#c42e46",
    note: "Yes, that's the real name. Deep red-pink skirt with a gold ring. The hobby names these things at 2am." },
  { id: "z20", name: "Scrambled Eggs", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#ffe98a", ring: "#ffb03a", mouth: "#fff4c4", center: "#ffd84d",
    note: "Creamy yellow through and through. Subtle rather than loud — a nice palette-cleanser next to screaming rainbow morphs." },
  { id: "z21", name: "Candy Apple Red", tier: "Mid", growth: "Slow", polyp: "Medium",
    skirt: "#e8465e", ring: "#ff7a5c", mouth: "#ffd84d", center: "#c42e46",
    note: "Saturated candy red. True reds are uncommon in zoas and this one is the benchmark. Slow but steady." },
  { id: "z22", name: "Tubbs Blue", tier: "Mid", growth: "Slow", polyp: "Medium",
    skirt: "#3f9bff", ring: "#5cc8ff", mouth: "#c4e8ff", center: "#2e6fd6",
    note: "One of the bluest zoas in the hobby. Needs good light to hold the color — it browns out in the shade." },
  { id: "z23", name: "Pink Zipper", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#ffb0c4", ring: "#e8465e", mouth: "#ffe98a", center: "#ff7a9e",
    note: "Pink skirt with a zippered red ring pattern. Photographs far better than it looks under white light — a blues coral." },
  { id: "z24", name: "Vivid Confusion", tier: "Mid", growth: "Moderate", polyp: "Large",
    skirt: "#6e3fbf", ring: "#3ce0a3", mouth: "#ff7a00", center: "#8f5cd6",
    note: "Purple, green, and orange all fighting for attention in one polyp. Chaotic in the best way." },
  { id: "z25", name: "Mind Trick", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#6e3fbf", mouth: "#ffd84d", center: "#2e8f6f",
    note: "Green skirt with a purple ring that seems to shift depending on the angle. Hence the name." },

  /* ---------- HIGH-END: the ones people plan purchases around ---------- */
  { id: "z26", name: "WWC Bounce Zoa", tier: "High-End", growth: "Slow", polyp: "Large",
    skirt: "#ff7a00", ring: "#ffd84d", mouth: "#e8465e", center: "#ff5d00",
    note: "World Wide Corals' signature morph. Big, inflated, almost bubbled polyps in molten orange. Slow grower, high price, big flex." },
  { id: "z27", name: "Krakatoa", tier: "High-End", growth: "Slow", polyp: "Large",
    skirt: "#ff5d00", ring: "#ffd84d", mouth: "#e8465e", center: "#c42e00",
    note: "Volcanic orange-red with a gold ring. A perennial want-list zoa that holds price better than most." },
  { id: "z28", name: "Magicians", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#6e3fbf", ring: "#3ce0a3", mouth: "#ffe98a", center: "#4a2680",
    note: "Deep purple with an electric green ring. Notoriously slow to multiply, which is exactly why it stays expensive." },
  { id: "z29", name: "Speckled Krakatoa", tier: "High-End", growth: "Slow", polyp: "Large",
    skirt: "#ff5d00", ring: "#ffe98a", mouth: "#ffd84d", center: "#e8465e",
    note: "Krakatoa with speckling across the skirt. The freckles are the whole value proposition and they take months to develop." },
  { id: "z30", name: "Jokers", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#8f5cd6", ring: "#ff7a00", mouth: "#3ce0a3", center: "#e8465e",
    note: "Purple, orange, and green in a genuinely bizarre combination. Rare enough that most people only see it in photos." },
  { id: "z31", name: "Sunkist Bam Bam", tier: "High-End", growth: "Moderate", polyp: "Large",
    skirt: "#ff9d3a", ring: "#3ce0a3", mouth: "#ffe98a", center: "#ff7a00",
    note: "The premium Bam Bam line — deeper orange, cleaner green ring, bigger polyps. Worth the premium over standard Bams." },
  { id: "z32", name: "Nirvana", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#ffb0c4", mouth: "#ffe98a", center: "#7dffb0",
    note: "Soft green with pink undertones — unusually delicate for a zoa. A collector's piece rather than a colony builder." },
  { id: "z33", name: "El Diablo", tier: "High-End", growth: "Slow", polyp: "Large",
    skirt: "#c42e46", ring: "#ff7a00", mouth: "#ffd84d", center: "#8f1a2e",
    note: "Deep devil red with fiery highlights. Big polyps that command attention at the center of a garden." },
  { id: "z34", name: "Pink Diamonds", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#ffb0c4", ring: "#ffe98a", mouth: "#fff4c4", center: "#ff7a9e",
    note: "Pale pink with glittering highlights across the skirt. Subtle, expensive, and photographs like a jewel." },
  { id: "z35", name: "Fruit Loops", tier: "High-End", growth: "Moderate", polyp: "Medium",
    skirt: "#ff7a9e", ring: "#3ce0a3", mouth: "#ffd84d", center: "#5cc8ff",
    note: "Every color in the box, exactly as the name promises. One of the busiest polyps in the hobby." },
  { id: "z36", name: "Space Monsters", tier: "High-End", growth: "Slow", polyp: "Large",
    skirt: "#6e3fbf", ring: "#5cc8ff", mouth: "#3ce0a3", center: "#8f5cd6",
    note: "Purple and blue with a green core — genuinely alien-looking. Slow, pricey, and a centerpiece morph." },
  { id: "z37", name: "Pandora", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#3f9bff", ring: "#8f5cd6", mouth: "#3ce0a3", center: "#2e6fd6",
    note: "Blue-purple gradient with green highlights. Named for Avatar and it earns it under actinics." },

  /* ---------- GRAIL: waiting lists and four figures ---------- */
  { id: "z38", name: "WWC Grand Master Krak", tier: "Grail", growth: "Very slow", polyp: "Large",
    skirt: "#ff5d00", ring: "#fff4c4", mouth: "#e8465e", center: "#ff7a00",
    note: "The Krakatoa line taken to its extreme. Single polyps have sold for four figures. Grows at a geological pace, which is precisely the problem." },
  { id: "z39", name: "Ultimate Zoa", tier: "Grail", growth: "Very slow", polyp: "Large",
    skirt: "#8f5cd6", ring: "#ffd84d", mouth: "#e8465e", center: "#3ce0a3",
    note: "A legendary rainbow morph that lives up to a very arrogant name. Availability is a rumor most of the year." },
  { id: "z40", name: "Kraken", tier: "Grail", growth: "Very slow", polyp: "Large",
    skirt: "#4a2680", ring: "#ff7a00", mouth: "#ffe98a", center: "#6e3fbf",
    note: "Deep purple with molten orange. One of the true grail zoas — expect a waiting list and a serious conversation with your spouse." },
  { id: "z41", name: "Grandis Paly (Gold)", tier: "High-End", growth: "Moderate", polyp: "Giant",
    skirt: "#ffd84d", ring: "#0d2620", mouth: "#3ce0a3", center: "#ffb03a",
    note: "Technically a Palythoa, not a zoa — polyps the size of a quarter with a gold skirt and green mouth. ⚠️ Grandis carry the highest palytoxin loads in the hobby: gloves, eye protection, and never handle them dry." },
  { id: "z42", name: "Sunny Side Up Paly", tier: "Mid", growth: "Fast", polyp: "Giant",
    skirt: "#ffe98a", ring: "#ffb03a", mouth: "#ff7a00", center: "#fff4c4",
    note: "Big cream-and-gold paly that looks like a fried egg. Fast grower for its size. Same palytoxin cautions as all Palythoa." },
  { id: "z43", name: "Devil's Armor Paly", tier: "Mid", growth: "Moderate", polyp: "Giant",
    skirt: "#8f1a2e", ring: "#ffd84d", mouth: "#3ce0a3", center: "#c42e46",
    note: "Dark red paly with a gold ring and green mouth. Dramatic at size. Handle with the usual Palythoa respect." },
  { id: "z44", name: "Alien Antivenom", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#5cc8ff", mouth: "#ffe98a", center: "#2ee6c8",
    note: "Green-teal with an icy blue ring. One of the cleaner-looking high-end morphs — restrained where most grails scream." },
  { id: "z45", name: "Twizzler", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#e8465e", ring: "#3ce0a3", mouth: "#ffd84d", center: "#ff7a9e",
    note: "Red-pink skirt with a green ring — reads exactly like the candy. A good value morph that grows well." },

  /* ---------- Added from hobby ID databases (Legendary Corals, AlgaeBarn, Tidal Gardens, CoralFish12g) ---------- */
  { id: "z46", name: "Sonic Flares", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#c8d0d8", ring: "#8fa0b0", mouth: "#e8eef2", center: "#a8b4c0",
    note: "One of the few morphs with a genuine metallic silver coloration — it looks almost chrome under LEDs. A standout in a sea of green and orange." },
  { id: "z47", name: "Frozen Hornets", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#ffd84d", ring: "#ffe98a", mouth: "#5cc8ff", center: "#3f9bff",
    note: "Bright yellow hornet ring and skirts wrapped around the icy blue center it's named for. A premium take on the hornet line." },
  { id: "z48", name: "Superstars", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#9e8fb8", ring: "#1a1a2e", mouth: "#c8b8d8", center: "#3a2f4f",
    note: "A very clean patterned zoa — contrasting black stripes over a metallic silver-purple body. Precision over loudness." },
  { id: "z49", name: "Pink Tasers", tier: "Mid", growth: "Moderate", polyp: "Small",
    skirt: "#0d0d1a", ring: "#ff7a9e", mouth: "#ffb0c4", center: "#1a1a2e",
    note: "Small pink dots surrounding an almost-black body — the contrast is striking and unusual. A collector's small-polyp morph." },
  { id: "z50", name: "Zombie Eyes", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#2e8f6f", ring: "#5cc8ff", mouth: "#e9f7fc", center: "#3f9bff",
    note: "Related to Seductions and White Zombies, but set apart by a clean blue-white ring and center. Eerie under blues." },
  { id: "z51", name: "Predators", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#a8c43a", ring: "#ff7a00", mouth: "#8f1a2e", center: "#6e1a3a",
    note: "Yellow-green skirts banded with orange over a dark maroon-purple base, with random red-orange speckling. Genuinely wild-looking." },
  { id: "z52", name: "Insane Rainbows", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#ff7a00", ring: "#3ce0a3", mouth: "#e8465e", center: "#ff5d00",
    note: "A bright orange body shot through with green and red around the center. One of the busier rainbow morphs." },
  { id: "z53", name: "Punch Drunk", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#3f9bff", ring: "#ff7a9e", mouth: "#ffb0c4", center: "#2e6fd6",
    note: "A unique combination of blue and pink rings — soft colors you don't often see paired in a single polyp." },
  { id: "z54", name: "Safecrackers", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#c42e46", ring: "#3f9bff", mouth: "#5cc8ff", center: "#8f1a2e",
    note: "A stunning metallic red body with blue centers. The metallic sheen is what elevates it above a standard red morph." },
  { id: "z55", name: "Mystiques", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#5cc8ff", ring: "#e9f7fc", mouth: "#ff7a9e", center: "#c42e46",
    note: "Cool blue and white splashes with crimson red tips and a pink center. A lot going on, and all of it works." },
  { id: "z56", name: "Banshees", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#ff7a00", ring: "#4a2680", mouth: "#3ce0a3", center: "#6e3fbf",
    note: "A blindingly bright orange skirt over a deep blue-purple body, punctuated by a green mouth. High contrast, high impact." },
  { id: "z57", name: "Prometheans", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#1a1a2e", ring: "#3a2f4f", mouth: "#5a2e9e", center: "#0d0d1a",
    note: "One of the few zoas that reads as genuinely 'black,' especially under blue LEDs. A moody, sought-after morph." },
  { id: "z58", name: "Blue Death Protopaly", tier: "Grail", growth: "Very slow", polyp: "Large",
    skirt: "#2e4fd6", ring: "#1a2e8f", mouth: "#5c6fff", center: "#0d1a5c",
    note: "A very rare and unique protopaly with an unusual blue-indigo coloration. Protopalys are a different beast — slow and coveted." },
  { id: "z59", name: "Rainbow Hornet", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#ff7a00", ring: "#4a2680", mouth: "#3ce0a3", center: "#3a2f6e",
    note: "A handsome deep purple-blue body with gorgeous metallic orange skirts — the rainbow entry in the prized Hornet lineage." },
  { id: "z60", name: "VW Bloodshots", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#a8b4c8", ring: "#8f6fb0", mouth: "#ff7a9e", center: "#6e3fbf",
    note: "Soft purple-pink centers surrounded by silver-blue hues. Subtle and clean rather than screaming for attention." },
  { id: "z61", name: "Aphrodite", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#ff7a00", ring: "#1a1a2e", mouth: "#ffd84d", center: "#0d0d1a",
    note: "Bright orange skirts, clean black stripes, and a bow-tie pattern around the mouth give it a genuinely polished look." },
  { id: "z62", name: "Orange Rainbows", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#ff7a00", ring: "#3ce0a3", mouth: "#e8465e", center: "#ff5d00",
    note: "One of the first 'Rainbow' zoas to hit the hobby — a piece of collector history that still looks great." },
  { id: "z63", name: "Goblins on Fire", tier: "Mid", growth: "Fast", polyp: "Medium",
    skirt: "#e8465e", ring: "#3ce0a3", mouth: "#7dffb0", center: "#c42e46",
    note: "A clean solid green center wrapped in fiery red skirts. Classic fire-and-green contrast done exceptionally well." },
  { id: "z64", name: "Blondies", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#ffe98a", ring: "#3f9bff", mouth: "#5cc8ff", center: "#2e6fd6",
    note: "A yellow body with solid blue centers. Cheerful, fast, and an easy way to get blue-and-yellow contrast on a budget." },
  { id: "z65", name: "Laffy Taffy", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#ff7a9e", ring: "#4a2680", mouth: "#ffd84d", center: "#6e3fbf",
    note: "Hot pink skirts, a deep purple body, and a yellow mouth — reads exactly like the candy it's named for." },
  { id: "z66", name: "Starfighters", tier: "Starter", growth: "Fast", polyp: "Small",
    skirt: "#ffe94d", ring: "#ffb03a", mouth: "#fff4c4", center: "#ffd84d",
    note: "Small polyps with lightning-yellow skirts. Fast grower that fills gaps in a garden with electric color." },
  { id: "z67", name: "Spongebobs", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#ffe94d", ring: "#ff7a00", mouth: "#fff4c4", center: "#ffd84d",
    note: "Named after the cartoon for obvious reasons — bright yellow through and through. Cheap, fast, and fun." },
  { id: "z68", name: "Sweet Tooth", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#ffb08a", ring: "#1a1a2e", mouth: "#ffd0b0", center: "#3a2f4f",
    note: "A bright peachy center framed by black markings around the face. Warm and unusual — peach is rare in zoas." },
  { id: "z69", name: "Circus", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#ffd84d", ring: "#ff9d3a", mouth: "#fff4c4", center: "#ffb03a",
    note: "A cousin of Blondies with a warmer, more golden-yellow hue. A cheerful, easy grower." },
  { id: "z70", name: "Emeralds on Fire", tier: "Mid", growth: "Fast", polyp: "Small",
    skirt: "#e8465e", ring: "#3ce0a3", mouth: "#7dffb0", center: "#c42e46",
    note: "Neon-bright green body and fiery red skirts. Small polyps, but the metallic colors punch well above their size." },
  { id: "z71", name: "Tiger Hornet", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#3f9bff", ring: "#ff7a00", mouth: "#ffd84d", center: "#2e6fd6",
    note: "Orange tiger-striped rings over a blue body. The striping is what sets it apart from the rest of the Hornet family." },
  { id: "z72", name: "LA Lakers", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#ffd84d", ring: "#6e3fbf", mouth: "#5cc8ff", center: "#8f5cd6",
    note: "Named for the basketball team's colors — all-yellow skirts with a bright blue center. A recognizable, well-loved morph." },
  { id: "z73", name: "Tutti Frutti", tier: "Starter", growth: "Fast", polyp: "Small",
    skirt: "#ffd84d", ring: "#ff7a00", mouth: "#ffe98a", center: "#ff9d3a",
    note: "A small polyp with a golden sunset yellow fading into an orange center. A sweet, cheap starter morph." },
  { id: "z74", name: "Gatorades", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#ff7a00", mouth: "#ffd84d", center: "#2e8f6f",
    note: "Named after the sports-drink colors — bright green and orange. Bold and energetic in a mixed garden." },
  { id: "z75", name: "King Jawbreakers", tier: "High-End", growth: "Slow", polyp: "Large",
    skirt: "#3a2f6e", ring: "#ff7a00", mouth: "#ffd84d", center: "#5a2e9e",
    note: "A clean, dark patterned body with a pop of orange from the ring. Big polyps and a premium price." },
  { id: "z76", name: "Snitches", tier: "Mid", growth: "Moderate", polyp: "Small",
    skirt: "#5cc8ff", ring: "#a8d8f0", mouth: "#ff7a9e", center: "#7ab8e0",
    note: "A sweet sky-blue body with a hint of pink in the center. Delicate coloring for a hardy little polyp." },
  { id: "z77", name: "ASD Atmospheres", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#7ab8e0", ring: "#c8e0f0", mouth: "#e9f7fc", center: "#5c9ed6",
    note: "A pastel blue body dusted with white speckles like a field of stars. One of the prettier 'galaxy' style morphs." },
  { id: "z78", name: "LC Antimatters", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#6e3fbf", ring: "#ff7a00", mouth: "#3ce0a3", center: "#8f5cd6",
    note: "Known for the beautiful range of shifting colors across its skirt. A modern collector morph that photographs incredibly." },
  { id: "z79", name: "Miami Vice", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#ff7a9e", mouth: "#ffd84d", center: "#2e8f6f",
    note: "A classic that never goes out of style — bright green skirts with hot pink. One of the enduring old-school names." },
  { id: "z80", name: "Mary Jane", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#ff7a00", mouth: "#ffd84d", center: "#2e8f6f",
    note: "A green-and-orange classic that stays affordable and grows reliably. A staple of the beginner zoa garden." },
  { id: "z81", name: "Blueberry Fields", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#5c8fd6", ring: "#3f6fb0", mouth: "#a8c8f0", center: "#2e4f8f",
    note: "An underrated baby-blue morph that's cheap and fast. One of the easiest ways to get true blue tones into a colony." },
  { id: "z82", name: "My Clementine", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#ff9d3a", ring: "#3ce0a3", mouth: "#ffe98a", center: "#ff7a00",
    note: "Bright citrus-orange skirts with green highlights. Named for the fruit and every bit as juicy under blues." },
  { id: "z83", name: "Tyree Space Monster", tier: "Grail", growth: "Very slow", polyp: "Large",
    skirt: "#6e3fbf", ring: "#5cc8ff", mouth: "#3ce0a3", center: "#4a2680",
    note: "A legendary Tyree line morph — purple and blue with a green core. A true collector grail with matching price tag." },
  { id: "z84", name: "Bloodshot", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#8f1a2e", ring: "#e8465e", mouth: "#ffd84d", center: "#c42e46",
    note: "Deep blood-red with fiery highlights — one of the rare-collector reds that drove the zoa mania of the last few years." },
  { id: "z85", name: "Tazer", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#3f9bff", ring: "#3ce0a3", mouth: "#ffe98a", center: "#2e6fd6",
    note: "An electric blue-green morph that lives up to its name under actinics. A modern high-end collector piece." },
  { id: "z86", name: "Bubble Buster", tier: "Grail", growth: "Very slow", polyp: "Large",
    skirt: "#ff7a00", ring: "#e8465e", mouth: "#ffd84d", center: "#ff5d00",
    note: "One of the ultimate-collector morphs — fiery, rare, and discussed on forums by its street value. A serious grail zoa." },
];

// Husbandry is the same across morphs — kept once rather than repeated 45 times.
export const ZOA_CARE = [
  ["Light", "Medium (75–150 PAR)"],
  ["Flow", "Low to medium"],
  ["Placement", "Anywhere — rock, sand, frag rack"],
  ["Feeding", "Optional; benefits from small foods"],
  ["Growth", "Spreads by budding new polyps"],
  ["Difficulty", "Easy — great beginner coral"],
  ["⚠️ SAFETY", "Palytoxin — gloves + eye protection when fragging"],
];

export const ZOA_TIPS = [
  ["Why won't they open?", "Almost always flow, a nipping fish, or zoa pox. Give them a few days after any move — zoas sulk before they settle."],
  ["Melting / disappearing polyps", "Check for zoa-eating nudibranchs (tiny, matched to the polyp color) and sundial snails. Dip and inspect the underside of the plug."],
  ["Colors washing out", "Usually too much light. Zoas color up best in the middle of the tank, not blasted at the top."],
  ["They won't spread", "Zoas grow toward food and light. Feed the tank, keep nutrients off zero, and be patient — they encrust when they're ready."],
];
