// Zoa & Paly morph guide.
//
// NOTE ON IMAGERY: named zoa morphs are hobbyist trade names, not species — there are no
// freely-licensed photos of "Utter Chaos" or "Rastas" the way there are for Amphiprion ocellaris.
// Every real photo of a named morph is a copyrighted vendor/hobbyist shot. So instead of faking
// photos, each morph carries its actual color signature (skirt / ring / mouth / center), which is
// exactly what reefers use to identify one, and the app renders an accurate polyp diagram from it.
//
// tier: rough market position — Starter (cheap, everywhere) → Grail (four figures, waiting lists)

export const ZOA_TIERS = ["All", "Starter", "Mid", "High-End", "Grail"];

export const ZOAS = [
  /* ---------- STARTER: bulletproof, cheap, fast growers ---------- */
  { id: "z1", name: "Green Bay Packers", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#ffd84d", mouth: "#ffe98a", center: "#2ee6c8",
    note: "Green skirt, yellow-gold center. The classic beginner zoa — nearly unkillable and multiplies like it's being paid to." },
  { id: "z2", name: "Radioactive Dragon Eye", tier: "Starter", growth: "Fast", polyp: "Large",
    skirt: "#3ce0a3", ring: "#ff7a00", mouth: "#ffd84d", center: "#ff5d00",
    note: "Neon green skirt with a blazing orange eye. One of the most recognizable zoas in the hobby and a rocket-fast grower." },
  { id: "z3", name: "Eagle Eye", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#2e8f6f", ring: "#1a3d2e", mouth: "#3ce0a3", center: "#0d2620",
    note: "Deep green with a dark, hawk-like center ring. Old-school, cheap, and grows in dense mats. A great filler between fancier colonies." },
  { id: "z4", name: "Fire and Ice", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#3fe3ff", ring: "#ff7a5c", mouth: "#ffd84d", center: "#ff5d72",
    note: "Icy blue skirt against a fiery orange center — the contrast is the whole point. Hardy and forgiving of nutrient swings." },
  { id: "z5", name: "Sunny D", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#ffb03a", ring: "#ff7a00", mouth: "#ffe98a", center: "#ffc24d",
    note: "Pure orange-gold sunburst. Cheap, cheerful, and grows fast enough to be a gateway drug into zoa collecting." },
  { id: "z6", name: "Green Hornet", tier: "Starter", growth: "Fast", polyp: "Large",
    skirt: "#3ce0a3", ring: "#0d2620", mouth: "#ffd84d", center: "#1a5c3a",
    note: "Big green polyps with a dark ring. Grows into a lawn if you let it — great for covering a rock fast." },
  { id: "z7", name: "Blue Hornet", tier: "Starter", growth: "Moderate", polyp: "Medium",
    skirt: "#3f9bff", ring: "#0d2040", mouth: "#3ce0a3", center: "#1a4a8f",
    note: "Blue skirt with green mouth. Colors pop hard under heavy actinics — a budget way to get blue into a colony." },
  { id: "z8", name: "Purple Death", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#8f5cd6", ring: "#3ce0a3", mouth: "#ffd84d", center: "#5a2e9e",
    note: "Purple skirt, green ring. Despite the metal name it's one of the most beginner-friendly zoas out there." },
  { id: "z9", name: "Armor of God", tier: "Starter", growth: "Moderate", polyp: "Medium",
    skirt: "#ffb03a", ring: "#6e3fbf", mouth: "#ffe98a", center: "#ff7a00",
    note: "Gold skirt with a purple ring. A staple in mixed colonies and reliably available at swaps." },
  { id: "z10", name: "Watermelon", tier: "Starter", growth: "Fast", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#ff5d72", mouth: "#ffb0c4", center: "#e8465e",
    note: "Green rim, pink-red flesh — reads exactly like the fruit. Fast, cheap, and a good confidence builder." },

  /* ---------- MID: the collector's bread and butter ---------- */
  { id: "z11", name: "Rastas", tier: "Mid", growth: "Fast", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#e8465e", mouth: "#ffd84d", center: "#ff7a00",
    note: "Green skirt, red ring, yellow mouth — the reggae colors that named it. Grows fast enough to fund a habit, which is why it's in every frag tank." },
  { id: "z12", name: "Utter Chaos", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#8f5cd6", ring: "#ff7a00", mouth: "#ffd84d", center: "#e8465e",
    note: "Purple skirt with a chaotic orange-red center that never looks the same twice. One of the most traded morphs in the hobby and a swap-table staple." },
  { id: "z13", name: "Bam Bam", tier: "Mid", growth: "Moderate", polyp: "Large",
    skirt: "#ff7a5c", ring: "#3ce0a3", mouth: "#ffe98a", center: "#ff5d00",
    note: "Orange skirt with a green ring and big fat polyps. A workhorse mid-tier zoa that colors up hard under blues." },
  { id: "z14", name: "Sunny Delight", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#ffd84d", ring: "#ff7a00", mouth: "#fff4c4", center: "#ffb03a",
    note: "A brighter, cleaner take on the orange sunburst. Slightly slower than Sunny D but noticeably more saturated." },
  { id: "z15", name: "Blue Agave", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#5cc8ff", ring: "#3ce0a3", mouth: "#ffd84d", center: "#2e9ed6",
    note: "Pale blue skirt with a green-gold center. Blues are rare in zoas, which is why this one holds its value." },
  { id: "z16", name: "Whammin' Watermelon", tier: "Mid", growth: "Moderate", polyp: "Large",
    skirt: "#3ce0a3", ring: "#e8465e", mouth: "#ffb0c4", center: "#ff5d72",
    note: "The upgraded watermelon — bigger polyps, deeper red, sharper green rim. Worth the step up from the basic version." },
  { id: "z17", name: "People Eater", tier: "Mid", growth: "Moderate", polyp: "Large",
    skirt: "#8f5cd6", ring: "#ffd84d", mouth: "#ff7a00", center: "#6e3fbf",
    note: "Purple skirt, gold ring, orange mouth. Big showy polyps that anchor a mixed zoa garden." },
  { id: "z18", name: "Nuclear Green", tier: "Mid", growth: "Fast", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#7dffb0", mouth: "#c4ffdc", center: "#2ee6c8",
    note: "Absurdly bright green all the way through. Under actinics it looks like it's plugged into a wall socket." },
  { id: "z19", name: "Gorilla Nipple", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#e8465e", ring: "#ffd84d", mouth: "#ff7a00", center: "#c42e46",
    note: "Yes, that's the real name. Deep red-pink skirt with a gold ring. The hobby names these things at 2am." },
  { id: "z20", name: "Scrambled Eggs", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#ffe98a", ring: "#ffb03a", mouth: "#fff4c4", center: "#ffd84d",
    note: "Creamy yellow through and through. Subtle rather than loud — a nice palette-cleanser next to screaming rainbow morphs." },
  { id: "z21", name: "Candy Apple Red", tier: "Mid", growth: "Slow", polyp: "Medium",
    skirt: "#e8465e", ring: "#ff7a5c", mouth: "#ffd84d", center: "#c42e46",
    note: "Saturated candy red. True reds are uncommon in zoas and this one is the benchmark. Slow but steady." },
  { id: "z22", name: "Tubbs Blue", tier: "Mid", growth: "Slow", polyp: "Medium",
    skirt: "#3f9bff", ring: "#5cc8ff", mouth: "#c4e8ff", center: "#2e6fd6",
    note: "One of the bluest zoas in the hobby. Needs good light to hold the color — it browns out in the shade." },
  { id: "z23", name: "Pink Zipper", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#ffb0c4", ring: "#e8465e", mouth: "#ffe98a", center: "#ff7a9e",
    note: "Pink skirt with a zippered red ring pattern. Photographs far better than it looks under white light — a blues coral." },
  { id: "z24", name: "Vivid Confusion", tier: "Mid", growth: "Moderate", polyp: "Large",
    skirt: "#6e3fbf", ring: "#3ce0a3", mouth: "#ff7a00", center: "#8f5cd6",
    note: "Purple, green, and orange all fighting for attention in one polyp. Chaotic in the best way." },
  { id: "z25", name: "Mind Trick", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#6e3fbf", mouth: "#ffd84d", center: "#2e8f6f",
    note: "Green skirt with a purple ring that seems to shift depending on the angle. Hence the name." },

  /* ---------- HIGH-END: the ones people plan purchases around ---------- */
  { id: "z26", name: "WWC Bounce Zoa", tier: "High-End", growth: "Slow", polyp: "Large",
    skirt: "#ff7a00", ring: "#ffd84d", mouth: "#e8465e", center: "#ff5d00",
    note: "World Wide Corals' signature morph. Big, inflated, almost bubbled polyps in molten orange. Slow grower, high price, big flex." },
  { id: "z27", name: "Krakatoa", tier: "High-End", growth: "Slow", polyp: "Large",
    skirt: "#ff5d00", ring: "#ffd84d", mouth: "#e8465e", center: "#c42e00",
    note: "Volcanic orange-red with a gold ring. A perennial want-list zoa that holds price better than most." },
  { id: "z28", name: "Magicians", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#6e3fbf", ring: "#3ce0a3", mouth: "#ffe98a", center: "#4a2680",
    note: "Deep purple with an electric green ring. Notoriously slow to multiply, which is exactly why it stays expensive." },
  { id: "z29", name: "Speckled Krakatoa", tier: "High-End", growth: "Slow", polyp: "Large",
    skirt: "#ff5d00", ring: "#ffe98a", mouth: "#ffd84d", center: "#e8465e",
    note: "Krakatoa with speckling across the skirt. The freckles are the whole value proposition and they take months to develop." },
  { id: "z30", name: "Jokers", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#8f5cd6", ring: "#ff7a00", mouth: "#3ce0a3", center: "#e8465e",
    note: "Purple, orange, and green in a genuinely bizarre combination. Rare enough that most people only see it in photos." },
  { id: "z31", name: "Sunkist Bam Bam", tier: "High-End", growth: "Moderate", polyp: "Large",
    skirt: "#ff9d3a", ring: "#3ce0a3", mouth: "#ffe98a", center: "#ff7a00",
    note: "The premium Bam Bam line — deeper orange, cleaner green ring, bigger polyps. Worth the premium over standard Bams." },
  { id: "z32", name: "Nirvana", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#ffb0c4", mouth: "#ffe98a", center: "#7dffb0",
    note: "Soft green with pink undertones — unusually delicate for a zoa. A collector's piece rather than a colony builder." },
  { id: "z33", name: "El Diablo", tier: "High-End", growth: "Slow", polyp: "Large",
    skirt: "#c42e46", ring: "#ff7a00", mouth: "#ffd84d", center: "#8f1a2e",
    note: "Deep devil red with fiery highlights. Big polyps that command attention at the center of a garden." },
  { id: "z34", name: "Pink Diamonds", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#ffb0c4", ring: "#ffe98a", mouth: "#fff4c4", center: "#ff7a9e",
    note: "Pale pink with glittering highlights across the skirt. Subtle, expensive, and photographs like a jewel." },
  { id: "z35", name: "Fruit Loops", tier: "High-End", growth: "Moderate", polyp: "Medium",
    skirt: "#ff7a9e", ring: "#3ce0a3", mouth: "#ffd84d", center: "#5cc8ff",
    note: "Every color in the box, exactly as the name promises. One of the busiest polyps in the hobby." },
  { id: "z36", name: "Space Monsters", tier: "High-End", growth: "Slow", polyp: "Large",
    skirt: "#6e3fbf", ring: "#5cc8ff", mouth: "#3ce0a3", center: "#8f5cd6",
    note: "Purple and blue with a green core — genuinely alien-looking. Slow, pricey, and a centerpiece morph." },
  { id: "z37", name: "Pandora", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#3f9bff", ring: "#8f5cd6", mouth: "#3ce0a3", center: "#2e6fd6",
    note: "Blue-purple gradient with green highlights. Named for Avatar and it earns it under actinics." },

  /* ---------- GRAIL: waiting lists and four figures ---------- */
  { id: "z38", name: "WWC Grand Master Krak", tier: "Grail", growth: "Very slow", polyp: "Large",
    skirt: "#ff5d00", ring: "#fff4c4", mouth: "#e8465e", center: "#ff7a00",
    note: "The Krakatoa line taken to its extreme. Single polyps have sold for four figures. Grows at a geological pace, which is precisely the problem." },
  { id: "z39", name: "Ultimate Zoa", tier: "Grail", growth: "Very slow", polyp: "Large",
    skirt: "#8f5cd6", ring: "#ffd84d", mouth: "#e8465e", center: "#3ce0a3",
    note: "A legendary rainbow morph that lives up to a very arrogant name. Availability is a rumor most of the year." },
  { id: "z40", name: "Kraken", tier: "Grail", growth: "Very slow", polyp: "Large",
    skirt: "#4a2680", ring: "#ff7a00", mouth: "#ffe98a", center: "#6e3fbf",
    note: "Deep purple with molten orange. One of the true grail zoas — expect a waiting list and a serious conversation with your spouse." },
  { id: "z41", name: "Grandis Paly (Gold)", tier: "High-End", growth: "Moderate", polyp: "Giant",
    skirt: "#ffd84d", ring: "#0d2620", mouth: "#3ce0a3", center: "#ffb03a",
    note: "Technically a Palythoa, not a zoa — polyps the size of a quarter with a gold skirt and green mouth. ⚠️ Grandis carry the highest palytoxin loads in the hobby: gloves, eye protection, and never handle them dry." },
  { id: "z42", name: "Sunny Side Up Paly", tier: "Mid", growth: "Fast", polyp: "Giant",
    skirt: "#ffe98a", ring: "#ffb03a", mouth: "#ff7a00", center: "#fff4c4",
    note: "Big cream-and-gold paly that looks like a fried egg. Fast grower for its size. Same palytoxin cautions as all Palythoa." },
  { id: "z43", name: "Devil's Armor Paly", tier: "Mid", growth: "Moderate", polyp: "Giant",
    skirt: "#8f1a2e", ring: "#ffd84d", mouth: "#3ce0a3", center: "#c42e46",
    note: "Dark red paly with a gold ring and green mouth. Dramatic at size. Handle with the usual Palythoa respect." },
  { id: "z44", name: "Alien Antivenom", tier: "High-End", growth: "Slow", polyp: "Medium",
    skirt: "#3ce0a3", ring: "#5cc8ff", mouth: "#ffe98a", center: "#2ee6c8",
    note: "Green-teal with an icy blue ring. One of the cleaner-looking high-end morphs — restrained where most grails scream." },
  { id: "z45", name: "Twizzler", tier: "Mid", growth: "Moderate", polyp: "Medium",
    skirt: "#e8465e", ring: "#3ce0a3", mouth: "#ffd84d", center: "#ff7a9e",
    note: "Red-pink skirt with a green ring — reads exactly like the candy. A good value morph that grows well." },
];

// Husbandry is the same across morphs — kept once rather than repeated 45 times.
export const ZOA_CARE = [
  ["Light", "Medium (75–150 PAR)"],
  ["Flow", "Low to medium"],
  ["Placement", "Anywhere — rock, sand, frag rack"],
  ["Feeding", "Optional; benefits from small foods"],
  ["Growth", "Spreads by budding new polyps"],
  ["Difficulty", "Easy — great beginner coral"],
  ["⚠️ SAFETY", "Palytoxin — gloves + eye protection when fragging"],
];

export const ZOA_TIPS = [
  ["Why won't they open?", "Almost always flow, a nipping fish, or zoa pox. Give them a few days after any move — zoas sulk before they settle."],
  ["Melting / disappearing polyps", "Check for zoa-eating nudibranchs (tiny, matched to the polyp color) and sundial snails. Dip and inspect the underside of the plug."],
  ["Colors washing out", "Usually too much light. Zoas color up best in the middle of the tank, not blasted at the top."],
  ["They won't spread", "Zoas grow toward food and light. Feed the tank, keep nutrients off zero, and be patient — they encrust when they're ready."],
];
